### ISSUE TITLE
Ink activation in atom

### ISSUE THREAD

**Issue by davidzentlermunro** [JunoLab/atom-ink#109]
I raised this in a previous thread, though that has been closed so trying a new one:

I got similar issues after installing an ink update. I tried uninstalling juno and julia and reinstalling, and now get the following error when julia automatically tries to install ink (atom tells me I have installed v0.6.2 of ink, v0.5.11 of julia and v0.1.1 of uber-juno): 

```
Failed to activate the ink package
_etch2.default.initialize is not a function
Hide Stack Trace
```
```
TypeError: _etch2.default.initialize is not a function
    at new PlotPane (C:/Users/uctpdtz/.atom/packages/ink/lib/plots/pane.js:22:10)
    at Function.fromId (C:/Users/uctpdtz/.atom/packages/ink/lib/util/pane-item.js:74:36)
    at Function.activate (C:/Users/uctpdtz/.atom/packages/ink/lib/plots/pane.js:12:26)
    at Object.module.exports.Ink.activate (file:///C:/Users/uctpdtz/.atom/packages/ink/lib/ink.coffee:23:9)
    at Package.module.exports.Package.activateNow (C:\Atom\resources\app.asar\src\package.js:183:20)
    at C:\Atom\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Atom\resources\app.asar\src\package.js:92:15)
    at C:\Atom\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Atom\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Atom\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\uctpdtz\.atom\packages\julia-client\node_modules\atom-package-deps\lib\index.js:29:35
    at [object Generator].next (native)
    at step (C:\Users\uctpdtz\.atom\packages\julia-client\node_modules\atom-package-deps\lib\index.js:59:191)
    at C:\Users\uctpdtz\.atom\packages\julia-client\node_modules\atom-package-deps\lib\index.js:59:368
    at process._tickCallback (node.js:392:9)
The error was thrown from the ink package. This issue has already been reported.
View Issue

```

**Comment by pfitzseb** [comment]
Does this only happen on installation or always when you start Atom?
Also, are you running the latest version of Atom?

**Comment by davidzentlermunro** [comment]
Always when I start Atom. I'm running v1,8.0 of atom.

**Comment by pfitzseb** [comment]
I'd recommend updating then -- current version is 1.12.9.

**Comment by davidzentlermunro** [comment]
thanks. I note atom should auto-update (I'm using on windows) but that doesn't seem to have happened. Would you recommend uninstalling and redownloading? In package settings, it says everything is up-to-date.

**Comment by pfitzseb** [comment]
If `Help` > `Check for Update` doesn't suggest the update, then yes, I'd download the latest version from atom.io and install that (afaik you don't need to uninstall first).

**Comment by davidzentlermunro** [comment]
Help does not have a Check for Update option in my version, so I'll try downloading and let you know how it goes with ink (unfortunately I need to get my network administrator to install the new version).

**Comment by davidzentlermunro** [comment]
Thanks that update has done the trick

**Comment by pfitzseb** [comment]
Sweet, glad you got that sorted! :)
