### ISSUE TITLE
Failed to activate the ink package

### ISSUE THREAD

**Issue by maacl** [JunoLab/atom-ink#114]
1. Start Atom

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.6.2

### Stack Trace

Failed to activate the ink package

```
At _etch2.default.initialize is not a function

TypeError: _etch2.default.initialize is not a function
    at new PlotPane (/home/mac/.atom/packages/ink/lib/plots/pane.js:22:10)
    at Function.fromId (/home/mac/.atom/packages/ink/lib/util/pane-item.js:74:36)
    at Function.activate (/home/mac/.atom/packages/ink/lib/plots/pane.js:12:26)
    at Object.module.exports.Ink.activate (/home/mac/.atom/packages/ink/lib/ink.coffee:23:9)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:183:20)
    at /opt/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:538:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:497:46)
    at /opt/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/mac/Dropbox/projects",
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.6.2
linter, v1.11.18
linter-clojure, v1.1.2
proto-repl, v1.4.12
proto-repl-charts, v0.4.0
recent-files-fuzzy-finder, v0.2.4
tool-bar, v1.0.1

# Dev
No dev packages
```

**Comment by pfitzseb** [comment]
Please update to a more recent version of Atom; you need at least 1.12, I think, though I'd recommend just using the latest version (1.13). I've added a minimum rquirement [here](https://github.com/JunoLab/atom-ink/commit/de481ab6af9b307a728c841b33dc31047ce949ed), but that won't come into effect until the next release.

**Comment by maacl** [comment]
Didn't realise I was this far behind. Works now.

**Comment by pfitzseb** [comment]
Great, glad you got it working!

**Comment by samuelbaute** [comment]
Hi!
Fresh install of last version of Atom and `uber-juno` and throw me this error (eager to have Juno functioning!!):

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.3


### Stack Trace

Failed to activate the ink package

```
At Cannot read property 'text' of undefined

TypeError: Cannot read property 'text' of undefined
    at render (/packages/ink/node_modules/etch/lib/render.js:6:18)
    at addChildren (/packages/ink/node_modules/etch/lib/render.js:39:24)
    at render (/packages/ink/node_modules/etch/lib/render.js:29:21)
    at Object.initialize (/packages/ink/node_modules/etch/lib/component-helpers.js:40:23)
    at Toolbar.Etch (/packages/ink/lib/util/etch.js:17:10)
    at /packages/ink/lib/util/etch.js:108:21)
    at render (/packages/ink/node_modules/etch/lib/render.js:17:25)
    at addChildren (/packages/ink/node_modules/etch/lib/render.js:39:24)
    at render (/packages/ink/node_modules/etch/lib/render.js:29:21)
    at Object.initialize (/packages/ink/node_modules/etch/lib/component-helpers.js:40:23)
    at /packages/ink/lib/plots/pane.js:24:10)
    at Function.fromId (/packages/ink/lib/util/pane-item.js:74:36)
    at Function.activate (/packages/ink/lib/plots/pane.js:14:28)
    at Object.activate (/packages/ink/lib/ink.coffee:23:9)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
ink 0.6.3 
julia-client 0.5.12 
language-julia 0.10.0 
latex-completions 0.3.2 
tool-bar 1.0.1 
uber-juno 0.1.1 
```

**Comment by ghost** [comment]
Hi, 
got the same problem as samuelbaute. Newest version of Atom and Julia just as refferd to in the installation guide 

Best
