### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by deepakagrawal** [JunoLab/atom-ink#117]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Linux Mint
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.6.2

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /home/deepak/.atom/packages/ink/lib/console/console.js:363

TypeError: Cannot read property 'dispose' of undefined
    at Console.resetPrefix (/home/deepak/.atom/packages/ink/lib/console/console.js:363:40)
    at atom-text-editor.coreMoveRight (/home/deepak/.atom/packages/ink/lib/console/console.js:47:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:31.8.0 core:move-up (input.hidden-input)
  2x -0:30.7.0 core:move-down (input.hidden-input)
  2x -0:29.2.0 core:backspace (input.hidden-input)
 13x -0:28.6.0 core:move-up (input.hidden-input)
 12x -0:21.1.0 core:move-left (input.hidden-input)
     -0:18 console:evaluate (input.hidden-input)
     -0:18 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
 13x -0:17.6.0 core:move-up (input.hidden-input)
     -0:12.8.0 console:evaluate (input.hidden-input)
     -0:12.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
 13x -0:12.5.0 core:move-up (input.hidden-input)
     -0:08.3.0 console:evaluate (input.hidden-input)
     -0:08.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  4x -0:07.8.0 core:move-up (input.hidden-input)
     -0:02.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:00.0 core:move-right (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.6.2 (active)
julia-client, v0.5.11 (active)
language-julia, v0.10.0 (active)
latex-completions, v0.3.2 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Datseris** [comment]
Just got this as well. Don't know how I can help. Tell me what information you might need. For me it happened simply when I pressed the up arrow to get the console history.

**Comment by pfitzseb** [comment]
I'm pretty sure this is fixed on master, so you should be good to go with the next release.

**Comment by softbrass** [comment]
1.13.1 ia32  I get this a lot when arrowing up and down in command history...

**Comment by sbromberger** [comment]
Happening to me with

Community Packages (7) /Users/bromberger1/.atom/packages
├── ink@0.6.3
├── julia-client@0.5.12
├── language-julia@0.10.0
├── latex-completions@0.3.2
├── mac-os-ui@0.3.0
├── tool-bar@1.0.1
└── uber-juno@0.1.1

on OSX:

```
TypeError: Cannot read property 'dispose' of undefined
    at Console.resetPrefix (/Users/me/.atom/packages/ink/lib/console/console.js:363:40)
    at /Users/me/.atom/packages/ink/lib/console/console.js:385:73
    at Function.module.exports.Emitter.simpleDispatch (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:527:32
    at Function.module.exports.Emitter.simpleDispatch (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayLayer.emitDidChangeSyncEvent (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:755:18)
    at /Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:682:29
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:681:41)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:664:12)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:868:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:822:14)
    at TextEditor.module.exports.TextEditor.transact (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1549:26)
    at /Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1126:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2522:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2488:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1124:19)
    at TextEditor.module.exports.TextEditor.backspace (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1115:19)
    at TextEditor.core:backspace (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:425:21)
    at /Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:666:34
    at TextBuffer.module.exports.TextBuffer.transact (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:819:18)
    at TextEditor.module.exports.TextEditor.transact (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1549:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:665:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/me/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
The error was thrown from the ink package. This issue has already been reported.
View Issue
```

**Comment by pfitzseb** [comment]
Should be fixed on ink master now. Not sure if my fix is 100% functionally correct, but at least I couldn't get it to blatantly error anymore ;-)

**Comment by merl-dev** [comment]
This issue has become paralyzing.  Any suggestions on how we might get the attempted bug fix into Juno?

**Comment by pfitzseb** [comment]
This shouldn't be happening anymore on the latest version. Feel free to reopen if it is though.
