### ISSUE TITLE
Uncaught TypeError: _this.getModel is not a function

### ISSUE THREAD

**Issue by malmaud** [JunoLab/atom-ink#118]
I'm getting this on the latest tagged version of all the Atom packages when pushing 'alt-down' or 'alt-up' in the console.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.6.2

### Stack Trace

Uncaught TypeError: _this.getModel is not a function

```
At /Users/malmaud/.atom/packages/ink/lib/console/console.js:58

TypeError: _this.getModel is not a function
    at ink-console.consolePreviousInHistory (/Users/malmaud/.atom/packages/ink/lib/console/console.js:58:49)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:06.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-light-ui)
     -0:04.5.0 console:evaluate (input.hidden-input)
     -0:04.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:00.0 console:previous-in-history (input.hidden-input)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "indent-detective",
      "symbols-view",
      "Hydrogen",
      "Jude",
      "atom-ctags"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (inactive)
atom-beautify, v0.29.17 (inactive)
atom-jade, v0.3.0 (active)
atom-jinja2, v0.6.0 (active)
atom-soda-dark-ui, v1.1.0 (inactive)
atomic-emacs, v0.9.2 (inactive)
file-icons, v2.0.13 (active)
git-history, v3.2.0 (inactive)
git-plus, v7.2.0 (active)
git-time-machine, v1.5.4 (inactive)
goto, v1.8.3 (inactive)
highlight-line, v0.12.0 (active)
ink, v0.6.2 (active)
julia-client, v0.5.11 (active)
language-bazel, v0.3.2 (active)
language-docker, v1.1.7 (active)
language-javascript-jsx, v0.3.7 (active)
language-julia, v0.10.0 (active)
language-latex, v1.0.0 (active)
language-lisp, v0.2.0 (active)
language-llvm, v0.1.1 (active)
language-lua, v0.9.11 (active)
language-matlab, v0.2.1 (active)
language-pbtxt, v0.3.1 (active)
language-protobuf, v0.7.1 (active)
language-rust, v0.4.9 (active)
language-x86, v1.0.1 (active)
last-cursor-position, v0.9.0 (active)
latex, v0.42.3 (inactive)
latex-completions, v0.3.2 (active)
merge-conflicts, v1.4.4 (active)
monokai, v0.19.0 (inactive)
Remote-FTP, v0.10.4 (active)
sync-settings, v0.8.1 (active)
unity-ui, v2.1.8 (inactive)
atom-dark-syntax, v0.28.0 (active)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (active)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by malmaud** [comment]
Bump, still getting this with everything updated.

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JunoLab/atom-ink/commit/825e7d8e6a2fd18cb71bc65e73ad810579cf7afc, but history is kinda broken...

**Comment by malmaud** [comment]
Thanks!
