### ISSUE TITLE
Uncaught TypeError: _this.previous is not a function

### ISSUE THREAD

**Issue by TrevorSavage** [JunoLab/atom-ink#124]
[Enter steps to reproduce:]

1. press the hotkey 'alt-up' with the console focused
3. This error is thrown

**Atom**: 1.14.4 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.4

### Stack Trace

Uncaught TypeError: _this.previous is not a function

```
At C:\Users\Trevor\.atom\packages\ink\lib\console\console.js:58

TypeError: _this.previous is not a function
    at /packages/ink/lib/console/console.js:58:49)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  3x -2:19.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  6x -1:30.2.0 core:backspace (input.hidden-input)
     -1:07.5.0 autocomplete-plus:cancel (atom-text-editor.editor)
     -0:51.5.0 console:evaluate (input.hidden-input)
     -0:51.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:48.7.0 core:move-up (input.hidden-input)
     -0:47.7.0 core:move-left (input.hidden-input)
     -0:45.2.0 console:evaluate (input.hidden-input)
     -0:45.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:37.8.0 console:previous-in-history (input.hidden-input)
     -0:34.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  3x -0:33.1.0 core:move-up (input.hidden-input)
 32x -0:29.4.0 core:backspace (input.hidden-input)
     -0:25.2.0 core:move-up (input.hidden-input)
     -0:24.1.0 console:previous-in-history (input.hidden-input)
     -0:21.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
ink 0.6.4 
julia-client 0.5.12 
language-julia 0.10.0 
latex-completions 0.3.2 
tool-bar 1.0.1 
uber-juno 0.1.1 
```

**Comment by deszoeke** [comment]
I have the same problem with ink in the julia console on MacOS El Capital 10.11.15.

**Comment by pfitzseb** [comment]
Alright, I've removed the `Alt-Up` and `Alt-Down` hotkeys in favour of just `Up` and `Down`, which work as advertised (and without the error reported here).

**Comment by WalterGR** [comment]
I ran into this exception.  Is there an estimated date for the next atom-ink release?  Many thanks for the package.

**Comment by pfitzseb** [comment]
The next release should be coming up relatively shortly. In the meantime you should be able to just use Cursor Up and Down to navigate the console.
