### ISSUE TITLE
Uncaught ReferenceError: bar is not defined

### ISSUE THREAD

**Issue by bjonica** [JunoLab/atom-ink#125]
1. Occurs when trying to open Proto REPL using the "Proto Repl: Toggle" command

I'm also using the 'custom' title bar option.

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.5

### Stack Trace

Uncaught ReferenceError: bar is not defined

```
At /Users/bjonica/.atom/packages/ink/lib/console/console.js:95

ReferenceError: bar is not defined
    at Console.render (console.js:95:5)
    at Object.initialize (/packages/ink/node_modules/etch/dist/component-helpers.js:60:34)
    at Console (console.js:77:10)
    at Function.fromId (pane-item.js:74:36)
    at InkConsole.module.exports.InkConsole.startConsole (/packages/proto-repl/lib/views/ink-console.coffee:29:29)
    at /packages/proto-repl/lib/views/ink-console.coffee:24:6)
    at Repl.module.exports.Repl.consumeInk (/packages/proto-repl/lib/repl.coffee:50:23)
    at Object.prepareRepl (/packages/proto-repl/lib/proto-repl.coffee:218:10)
    at Object.toggle (/packages/proto-repl/lib/proto-repl.coffee:211:8)
    at /packages/proto-repl/lib/proto-repl.coffee:112:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:92:28)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:292:20)
    at /app.asar/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:47.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-contrast.compact-tree-view.theme-nord-atom-syntax.theme-atom-material-ui)
     -0:20.6.0 core:close (div.panels-item)
     -0:11.8.0 command-palette:toggle (input.hidden-input)
     -0:09.7.0 core:confirm (input.hidden-input)
     -0:09.7.0 proto-repl:toggle (input.hidden-input)
     -0:07.7.0 command-palette:toggle (input.hidden-input)
     -0:06.2.0 core:confirm (input.hidden-input)
     -0:06.2.0 proto-repl:toggle (input.hidden-input)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
aurora-theme 1.2.2 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
build 0.67.0 
build-cargo 2.0.0 
build-gradle 0.6.0 
build-npm-apm 0.12.0 
busy 0.7.0 
docblockr 0.9.1 
file-icons 2.0.17 
firewatch-syntax 1.1.1 
fonts 2.0.0 
format-graphql 0.1.2 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
git-diff-details 1.4.0 
git-plus 7.3.3 
git-time-machine 1.5.6 
github-atom-light-syntax 0.3.2 
highlight-selected 0.12.0 
ink 0.6.5 
language-elm 1.5.0 
language-gradle 0.0.3 
language-graphql 0.8.0 
language-groovy 0.6.0 
language-rust 0.4.9 
language-terraform 0.7.5 
linter 1.11.23 
linter-elm-make 0.22.5 
linter-eslint 8.1.3 
linter-flow 5.5.0 
linter-rust 0.7.2 
linter-write-good 0.8.0 
linter-xmllint 1.4.1 
lisp-paredit 0.5.5 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-codeglance 0.4.5 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-linter 1.6.0 
native-ui 0.20.4 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.2 
Parinfer 1.17.0 
pinned-tabs 0.4.2 
proto-repl 1.4.16 
proto-repl-sayid 0.1.4 
react 0.16.2 
script 3.14.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
swackets 0.26.0 
tablr 1.8.1 
xml-formatter 0.10.0 
you-complete-me 0.7.11 
Zen 0.16.4 
zentabs 0.8.8 
```

**Comment by tafenton** [comment]
Hi all,

I've been able to return to a working state by reverting to an earlier version...
"apm install ink@0.6.1"
Hopefully this will keep a few people working until a fix is published!

Tom

**Comment by pfitzseb** [comment]
I can't reproduce this with latest proto-repl and ink. And I couldn't find any `custom title` option anywhere -- was that deprecated or something?

If you're still getting that error with the latest ink version, feel free to reopen.

**Comment by tafenton** [comment]
Hi pfitzseb,
Both bjonica and I are using Atom beta - Atom stable is currently unaffected, although I assume the next update will be! If you want to try that you should be able to reproduce it.

**Comment by pfitzseb** [comment]
Well, 1.16 is stable now. Will try with 1.17 beta though.

**Comment by pfitzseb** [comment]
Alright, can't reproduce this with ink master and atom 1.17 beta either. Seems to be fixed...

**Comment by bjonica** [comment]
Yep, this was an issue in beta. Works for me now as well.

**Comment by tafenton** [comment]
Yes all looks good post-update, thanks for investigating!
