### ISSUE TITLE
Uncaught TypeError: _this3.remove is not a function

### ISSUE THREAD

**Issue by KristofferC** [JunoLab/atom-ink#135]
Not sure what I did, maybe i removed an inline result box. Not sure the error is with this package even :)

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: elementary OS
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.5

### Stack Trace

Uncaught TypeError: _this3.remove is not a function

```
At /home/kristoffer/.atom/packages/ink/lib/editor/result-view.js:78

TypeError: _this3.remove is not a function
    at HTMLDivElement.inlineResultsClear (/packages/ink/lib/editor/result-view.js:78:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:51.2.0 core:save (input.hidden-input)
     -0:50.9.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:50.7.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:47.1.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:47 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:46.2.0 core:save (input.hidden-input)
     -0:36.5.0 command-palette:toggle (input.hidden-input)
     -0:35.6.0 core:confirm (input.hidden-input)
     -0:35.6.0 julia-client:kill-julia (input.hidden-input)
     -0:26.9.0 core:move-down (input.hidden-input)
     -0:26.6.0 julia-client:run-and-move (input.hidden-input)
 10x -0:26.1.0 core:move-up (input.hidden-input)
     -0:24.7.0 core:move-down (input.hidden-input)
  9x -0:24.5.0 core:select-down (input.hidden-input)
  2x -0:18.5.0 julia-client:run-and-move (input.hidden-input)
     -0:06.5.0 inline-results:clear (span.syntax--support.syntax--type)
```

### Non-Core Packages

```
ink 0.6.5 
julia-client 0.5.12 
language-julia 0.11.0 
latex-completions 0.3.2 
monokai 0.24.0 
tool-bar 1.1.0 
uber-juno 0.1.1 
```

**Comment by pfitzseb** [comment]
Thanks for reporting -- should be fixed now. For the record, this happened when using the "Clear" entry in the result's context menu.
