### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by spiralizing** [JunoLab/atom-ink#138]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 14.04.5
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /home/alfredo/.atom/packages/ink/lib/editor/result-view.js:106

TypeError: Cannot read property 'classList' of undefined
    at ResultView.setContent (/packages/ink/lib/editor/result-view.js:106:23)
    at ResultView.content (/packages/ink/lib/editor/result-view.js:83:23)
    at ResultView.completeView (/packages/ink/lib/editor/result-view.js:46:36)
    at /packages/ink/lib/editor/result-view.js:10:10)
    at /packages/ink/lib/editor/result.js:23:17)
    at /packages/julia-client/lib/runtime/evaluation.coffee:35:33
```

### Commands

```
  2x -0:35.3.0 julia-client:run-and-move (input.hidden-input)
```

### Non-Core Packages

```
batman-syntax 1.1.0 
ink 0.7.1 
julia-client 0.6.0 
language-julia 0.11.0 
latex-completions 0.3.2 
minimap 4.28.2 
```

**Comment by shhong** [comment]
I still get this error whenever I click "Start Remote Julia Process" toolbar

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.13.6
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.14


### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At /Users/shhong/.atom/packages/ink/node_modules/xterm/lib/InputHandler.js:724

TypeError: Cannot read property 'classList' of undefined
    at InputHandler.setMode (/packages/ink/node_modules/xterm/lib/InputHandler.js:724:44)
    at /packages/ink/node_modules/xterm/lib/InputHandler.js:106:84)
    at EscapeSequenceParser.parse (/packages/ink/node_modules/xterm/lib/EscapeSequenceParser.js:401:40)
    at InputHandler.parse (/packages/ink/node_modules/xterm/lib/InputHandler.js:183:22)
    at Terminal._innerWrite (/packages/ink/node_modules/xterm/lib/Terminal.js:907:32)
    at /packages/ink/node_modules/xterm/lib/Terminal.js:889:23
```

### Commands

```
     -0:05.1.0 julia-client:start-remote-julia-process (input.hidden-input)
```

### Non-Core Packages

```
ayu 0.1.0 
Hydrogen 2.8.0 
ink 0.9.14 
julia-client 0.7.13 
seti-syntax 1.2.0 
seti-ui 1.11.0 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
That's a different error; see https://github.com/JunoLab/Juno.jl/issues/226. Should be fixed in one of the next releases. You should be able to work around this by opening the REPL first and then starting the remote process.
