### ISSUE TITLE
Uncaught Error: Tried to create a gutter with a name that is already in use.

### ISSUE THREAD

**Issue by ryhan123** [JunoLab/atom-ink#141]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.7.4

### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app/src/gutter-container.js:36:21)
    at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3157:41)
    at BreakpointManager.init (/packages/ink/lib/debugger/breakpoints.js:68:16)
    at /packages/ink/lib/debugger/breakpoints.js:41:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.handleGrammarChange (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3323:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:122:33)
    at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2895:41)
    at TextEditorRegistry.selectGrammarForEditor (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:353:22)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:251:22
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:520:38
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.setPath (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:337:33)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1122:18)
    at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:929:32)
    at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app/src/pane.js:808:22)
    at Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:792:27)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
```

### Commands

```
     -0:55.7.0 core:save (input.hidden-input)
     -0:20.2.0 application:open-file (input.hidden-input)
     -0:07.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.1.1 
ink 0.7.4 
julia-client 0.6.0 
language-julia 0.11.0 
latex-completions 0.3.2 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by pfitzseb** [comment]
Hm, can you give some information on what you were doing when this happened?

**Comment by ryhan123** [comment]
I was creating a new file named “tictactoe.jl"
-----------------------------------------------
Ryhan Moghe
Ridge High School Class of 2018

Email: ryhan.moghe@gmail.com
Mobile: 908-240-1784

**Comment by pfitzseb** [comment]
Alright, and can you reproduce the error (I can't, so it's pretty difficult to track down the exact cause of this)?

**Comment by ryhan123** [comment]
It hasn’t happened to me since yesterday, so I’m not sure what the exact cause was
-----------------------------------------------
Ryhan Moghe
Ridge High School Class of 2018

Email: ryhan.moghe@gmail.com
Mobile: 908-240-1784

**Comment by pfitzseb** [comment]
Should be fixed now.
