### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ohduran** [JunoLab/atom-ink#143]
[Enter steps to reproduce:]

1. Calling a big json will return this error, but won't block the processing of the .py file

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.7.4

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /home/alvaro/.atom/packages/ink/node_modules/ansi-to-html/lib/ansi_to_html.js:370

RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.[Symbol.match] (native)
    at String.match (native)
    at process (/packages/ink/node_modules/ansi-to-html/lib/ansi_to_html.js:370:24)
    at Filter.tokenize (/packages/ink/node_modules/ansi-to-html/lib/ansi_to_html.js:380:11)
    at /packages/ink/node_modules/ansi-to-html/lib/ansi_to_html.js:142:24
    at Array.forEach (native)
    at Filter.forEach (/packages/ink/node_modules/ansi-to-html/lib/ansi_to_html.js:139:18)
    at Filter.toHtml (/packages/ink/node_modules/ansi-to-html/lib/ansi_to_html.js:129:12)
    at ScriptView.display (/packages/script/lib/script-view.js:179:28)
    at /packages/script/lib/view-runtime-observer.js:16:71
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Runner.stdoutFunc (/packages/script/lib/runner.js:45:18)
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
  5x -2:51.8.0 core:backspace (input.hidden-input)
     -2:41 intentions:highlight (input.hidden-input)
     -2:40.8.0 core:save (input.hidden-input)
     -2:38.9.0 intentions:highlight (input.hidden-input)
     -2:38.7.0 script:run (input.hidden-input)
     -2:12.3.0 editor:copy-path (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -2:01.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
  3x -1:43.7.0 core:backspace (input.hidden-input)
     -0:37.3.0 intentions:highlight (input.hidden-input)
     -0:37.1.0 core:save (input.hidden-input)
  2x -0:29.2.0 core:backspace (input.hidden-input)
     -0:27.8.0 intentions:highlight (input.hidden-input)
     -0:27.6.0 core:save (input.hidden-input)
  2x -0:21.9.0 core:backspace (input.hidden-input)
     -0:15.5.0 intentions:highlight (input.hidden-input)
     -0:15.3.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
dash 1.7.1 
data-atom 0.25.2 
emmet 2.4.3 
file-icons 2.1.9 
indent-detective 0.1.1 
ink 0.7.4 
intentions 1.1.2 
latex-completions 0.3.3 
linter 2.2.0 
linter-flake8 2.2.1 
linter-ui-default 1.6.3 
linter-write-good 0.9.0 
markdown-preview-plus 2.4.10 
markdown-writer 2.6.5 
monokai-seti 0.9.0 
save-session 0.15.7 
script 3.15.0 
terminal-plus 0.14.5 
tool-bar 1.1.0 
wakatime 7.0.3 
```

**Comment by pfitzseb** [comment]
Hm, I'm relatively sure this is an issue with https://github.com/rgbkrk/atom-script that just happens to point to ink because the package manager happens to reuse our `ansi-to-html` dependency for atom-script.

Would probably be best to deactivate ink for now and try again (unless one of the packages you use requires it, but I don't think so).
