### ISSUE TITLE
Try to install ink 0.8.1 but failed to activate the ink package

### ISSUE THREAD

**Issue by jungangl** [JunoLab/atom-ink#161]
Tried to create a gutter with a name that is already in use.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.8.1

### Stack Trace

Failed to activate the ink package

```
At Tried to create a gutter with a name that is already in use.

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.addGutter (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/gutter-container.js:33:19)
    at TextEditor.addGutter (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/text-editor.js:3935:39)
    at BreakpointManager.init (/packages/ink/lib/debugger/breakpoints.js:68:16)
    at /packages/ink/lib/debugger/breakpoints.js:41:16
    at TextEditor.observeGrammar (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/text-editor.js:727:11)
    at /packages/ink/lib/debugger/breakpoints.js:39:24
    at Workspace.observeTextEditors (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/workspace.js:725:15)
    at /packages/ink/lib/debugger/breakpoints.js:38:34)
    at Object.consumeInk (/packages/julia-client/lib/runtime/debugger.js:123:17)
    at Object.consumeInk (/packages/julia-client/lib/runtime.coffee:23:15)
    at Object.consumeInk (/packages/julia-client/lib/julia-client.coffee:38:7)
    at Provider.module.exports.Provider.provide (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/package.js:448:77)
    at Package.module.exports.Package.activateNow (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/package.js:258:22)
    at /Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/Users/jungangl/Documents/Programming Languages/Julia/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -8:05.2.0 julia-client:open-console (div.package-detail.panels-item)
  4x -7:38.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  3x -6:12.9.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -4:56.9.0 settings-view:install-packages-and-themes (textarea.xterm-helper-textarea)
  3x -4:26.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:13 core:paste (input.hidden-input)
  2x -3:12.7.0 core:confirm (input.hidden-input)
     -2:05.5.0 julia-client:open-console (input.hidden-input)
     -1:47.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-latex 0.8.4 
city-lights-syntax 1.1.6 
cucumber 0.6.0 
Hydrogen 2.2.2 
ide-haskell 2.2.3 
ink 0.8.1 
julia-client 0.6.7 
language-julia 0.15.0 
language-latex 1.1.1 
latex 0.49.0 
latex-completions 0.3.3 
platformio-ide-terminal 2.8.0 
print-atom 0.1.1 
python-tools 0.6.9 
rbox 0.2.1 
script 3.17.3 
seti-icons 1.5.4 
solarized-dark-ui 0.3.2 
tool-bar 1.1.4 
uber-juno 0.1.2 
zentabs 0.8.9 
```

**Comment by pfitzseb** [comment]
Should be fixed on master.
