### ISSUE TITLE
Uncaught TypeError: Cannot read property 'domNode' of undefined

### ISSUE THREAD

**Issue by V1talyK** [JunoLab/atom-ink#173]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Linux Mint
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.6

### Stack Trace

Uncaught TypeError: Cannot read property 'domNode' of undefined

```
At /home/lik/.atom/packages/ink/node_modules/etch/lib/patch.js:5

TypeError: Cannot read property 'domNode' of undefined
    at patch (/packages/ink/node_modules/etch/lib/patch.js:5:34)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:112:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/ink/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:238:13)
```

### Commands

```
  3x -3:21.7.0 tree-view:collapse-directory (div.tool-panel.tree-view)
     -0:14.6.0 julia-client:run-block (input.hidden-input)
     -0:14.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
  7x -0:09.8.0 core:move-left (input.hidden-input)
     -0:08.2.0 core:delete (input.hidden-input)
     -0:07.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:07.3.0 julia-client:run-block (input.hidden-input)
     -0:07.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
highlight-selected 0.14.0 
ink 0.9.6 
julia-client 0.7.6 
language-julia 0.17.0 
latex-completions 0.3.5 
line-count 0.5.0 
tool-bar 1.1.10 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
What were you doing when that error appeared?

**Comment by V1talyK** [comment]
I stop Julia (from top menu Julia -> Stop Julia) and then there was this error appeared. At the same time workspase remained unchanged and did not react to any changes, even after a new start of Julia or pressing the " update" button.

**Comment by pfitzseb** [comment]
Should be fixed now.

**Comment by baggepinnen** [comment]
This error appeared for me now, after just having updated atom to 1.40.1, debuginfo below
```
# Atom:
Version: 1.40.1
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.10.1
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "noAutoParenthesis": true
  },
  "juliaPath": "/home/fredrikb/julia-1.3.0-alpha/bin/julia",
  "uiOptions": {
    "enableMenu": true,
    "errorNotifications": false,
    "layouts": {
      "console": {
        "defaultLocation": "center",
        "split": "right"
      },
      "defaultPanes": {
        "documentation": false,
        "plotPane": false,
        "workspace": false
      },
      "openDefaultPanesOnStartUp": false,
      "plotPane": {
        "split": "up"
      }
    },
    "usePlotPane": false
  }
}


# ink:
Version: 0.11.0
Config:
undefined


# uber-juno:
Version: 0.2.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.1
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


Julia Version 1.3.0-alpha.0
Commit 6c11e7c2c4 (2019-07-23 01:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = atom  -a

    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.10.1
  [70b36510] AutomaticDocstrings v0.1.1 [`~/.julia/dev/AutomaticDocstrings`]
  [aae01518] BandedMatrices v0.10.1
  [07f847a3] BasisFunctionExpansions v1.0.1
  [6e4b80f9] BenchmarkTools v0.4.3
  [5d742f6a] CSVFiles v0.16.0
  [3895d2a7] CUDAapi v1.1.0
  [8f4d0f93] Conda v1.3.0
  [3abffc1c] ControlSystemIdentification v0.1.5 [`~/.julia/dev/ControlSystemIdentification`]
  [a6e380b2] ControlSystems v0.5.3
  [3a865a2d] CuArrays v1.3.0 #master (https://github.com/JuliaGPU/CuArrays.jl.git)
  [717857b8] DSP v0.6.0
  [a93c6f00] DataFrames v0.19.3
  [864edb3b] DataStructures v0.17.0
  [9cd584b6] DifferentialDynamicProgramming v0.4.0 [`~/.julia/dev/DifferentialDynamicProgramming`]
  [09c11fbc] DiskDataProviders v0.1.0 [`~/.julia/dev/DiskDataProviders`]
  [7a1cc6ca] FFTW v0.3.0
  [5789e2e9] FileIO v1.0.7
  [587475ba] Flux v0.9.0 [`~/.julia/dev/Flux`]
  [ca11d760] FluxOptTools v0.1.0 [`~/.julia/dev/FluxOptTools`]
  [f6369f11] ForwardDiff v0.10.3
  [28b8d3ca] GR v0.41.0
  [14197337] GenericLinearAlgebra v0.1.1
  [f67ccb44] HDF5 v0.12.3
  [cd3eb016] HTTP v0.8.5
  [7073ff75] IJulia v1.20.0
  [6a3955dd] ImageFiltering v0.6.5
  [6218d12a] ImageMagick v0.7.5
  [916415d5] Images v0.18.0
  [d0351b0e] InspectDR v0.3.6
  [e5e0dc1b] Juno v0.7.2
  [1902f260] Knet v1.2.5
  [26dcc766] LPVSpectral v0.1.2
  [82ba68a1] LazyWAVFiles v0.1.0 [`~/.julia/dev/LazyWAVFiles`]
  [98b081ad] Literate v2.0.3
  [43172d54] LiterateWeave v0.1.0 [`~/.julia/dev/LiterateWeave`]
  [33e6dc65] MKL v0.0.0 #master (https://github.com/JuliaComputing/MKL.jl)
  [f0e99cf1] MLBase v0.8.0
  [cc2ba9b6] MLDataUtils v0.5.0
  [0987c9cc] MonteCarloMeasurements v0.4.1 [`~/.julia/dev/MonteCarloMeasurements`]
  [6f286f6a] MultivariateStats v0.7.0
  [872c559c] NNlib v0.6.0
  [429524aa] Optim v0.19.2
  [1dea7af3] OrdinaryDiffEq v5.15.1
  [58dd65bb] Plotly v0.2.0
  [f0f68f2c] PlotlyJS v0.12.5
  [91a5bcdd] Plots v0.26.2
  [3a141323] PolynomialRoots v0.2.0
  [438e738f] PyCall v1.91.2
  [d330b81b] PyPlot v2.8.2
  [a75dfa10] Robotlib v0.3.2+ [`~/.julia/dev/Robotlib`]
  [90137ffa] StaticArrays v0.11.0
  [2913bbd2] StatsBase v0.30.0
  [f3b207a7] StatsPlots v0.12.0
  [bd369af6] Tables v0.2.11
  [5e47fb64] TestImages v0.5.1
  [c751599d] ToeplitzMatrices v0.6.0
  [b8865327] UnicodePlots v1.1.0
  [8149f6b0] WAV v1.0.2
  [44d3d7a6] Weave v0.9.1
  [cd998857] Yota v0.1.3+ [`~/.julia/dev/Yota`]
  [e88e6eb3] Zygote v0.3.4 #master (https://github.com/FluxML/Zygote.jl.git)
  [700de1a5] ZygoteRules v0.1.0 [`~/.julia/dev/ZygoteRules`]

```

**Comment by pmarg** [comment]
Yes, I face the same in Windows:

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Education
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0


### Stack Trace

Uncaught TypeError: Cannot read property 'domNode' of undefined

```
At C:\Users\PA.4471\.atom\packages\ink\node_modules\etch\lib\patch.js:5

TypeError: Cannot read property 'domNode' of undefined
    at patch (/packages/ink/node_modules/etch/lib/patch.js:5:34)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:112:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/ink/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:325676)
```

### Commands

```
     -2:33.7.0 editor:newline (input.hidden-input)
  3x -2:31.3.0 core:backspace (input.hidden-input)
     -2:29.4.0 intentions:highlight (input.hidden-input)
     -2:29.3.0 core:save (input.hidden-input)
     -2:25.8.0 intentions:highlight (input.hidden-input)
     -2:25.5.0 core:copy (input.hidden-input)
     -2:22.6.0 editor:newline (input.hidden-input)
     -2:22.5.0 intentions:highlight (input.hidden-input)
     -2:22.4.0 core:paste (input.hidden-input)
     -2:22 intentions:highlight (input.hidden-input)
     -2:21.8.0 core:save (input.hidden-input)
     -2:05.9.0 intentions:highlight (input.hidden-input)
     -2:05.8.0 core:save (input.hidden-input)
     -2:01.4.0 julia-client:run-all (input.hidden-input)
     -2:01.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:01.4.0 inline-results:clear-all (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
aligner-javascript 1.3.0 
atom-alignment 0.13.0 
atom-clock 0.1.17 
atom-language-r 1.4.8 
busy-signal 2.0.1 
file-icons 2.1.35 
Hydrogen 2.12.0 
indent-detective 0.4.0 
ink 0.11.0 
intentions 1.1.5 
julia-client 0.10.1 
language-fortran 2.1.9 
language-julia 0.19.1 
language-latex 1.2.0 
language-markdown 0.37.0 
language-matlab 0.2.1 
language-stata 1.7.3 
latex 0.50.2 
latex-autocomplete 1.1.1 
latex-completions 0.3.6 
latexer 0.3.0 
linter 2.3.1 
linter-julia 0.7.4 
linter-markdown 5.2.9 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.0 
markdown-preview-enhanced 0.16.3 
mathjax-wrapper 0.1.0 
monokai 0.24.0 
pdf-view 0.72.0 
remote-ftp 2.2.2 
sync-settings 0.8.6 
tasks 2.10.1 
terminal-tab 0.5.7 
todo-show 2.3.2 
tool-bar 1.1.12 
uber-juno 0.2.0 
Zen 0.18.0 
```

**Comment by tlienart** [comment]
and you can get sequences of those which reappear quickly after closing 😢 : 

![Screen Shot 2019-09-11 at 14 50 36](https://user-images.githubusercontent.com/10897531/64698730-b3a1e480-d4a3-11e9-8708-9eea556a000c.png)

**Comment by Petr-Hlavenka** [comment]
I see exactly the same problem.
[Enter steps to reproduce:]
1. happens usually after I do `include(script.jl)`
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0


### Stack Trace

Uncaught TypeError: Cannot read property 'domNode' of undefined

```
At C:\Users\petr.hlavenka\.atom\packages\ink\node_modules\etch\lib\patch.js:5

TypeError: Cannot read property 'domNode' of undefined
    at patch (/packages/ink/node_modules/etch/lib/patch.js:5:34)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:112:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/ink/node_modules/etch/lib/component-helpers.js:72:7
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:325676)
```

### Commands

```
     -2:27.5.0 core:save (input.hidden-input)
     -2:23.7.0 core:move-down (input.hidden-input)
     -2:23.5.0 core:move-up (input.hidden-input)
     -2:20.5.0 core:move-down (input.hidden-input)
     -2:20.4.0 core:move-up (input.hidden-input)
     -2:14.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:13.7.0 julia-client:run-block (input.hidden-input)
     -2:13.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:09.6.0 core:move-down (input.hidden-input)
     -2:09.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -2:04.5.0 julia-client:run-and-move (input.hidden-input)
     -0:47.1.0 core:delete (input.hidden-input)
     -0:46 core:paste (input.hidden-input)
     -0:43.5.0 core:move-right (input.hidden-input)
     -0:42.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:39 julia-client:run-and-move (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-ide-datatip 0.11.0 
atom-ide-markdown-service 1.2.3 
busy-signal 2.0.1 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.11.0 
julia-client 0.10.1 
language-julia 0.19.1 
language-weave 0.6.4 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
This will be fixed in the next ink release.
