### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pvazteixeira** [JunoLab/atom-ink#178]
Trying to evaluate a block starting from line 1 (Shift+Alt+Enter):

```julia
#---
using TransformUtils
```

Doing this will cause Atom to either throw the error message below or crash. This happens under both Atom 1.29 and 1.30.

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 18.04.1
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.7

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/pvt/dotfiles/atom/.atom/packages/ink/lib/editor/result.js:43

TypeError: Cannot read property 'length' of undefined
    at Result.attach (/packages/ink/lib/editor/result.js:43:84)
    at /packages/ink/lib/editor/result.js:24:10)
    at /packages/julia-client/lib/runtime/evaluation.coffee:38:29
```

### Commands

```
     -0:17.8.0 core:move-up (input.hidden-input)
  2x -0:17.1.0 julia-client:run-cell-and-move (input.hidden-input)
     -0:05.4.0 core:move-up (input.hidden-input)
  2x -0:05.2.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.3.0 
ink 0.9.7 
julia-client 0.7.6 
language-julia 0.17.0 
latex-completions 0.3.5 
teletype 0.13.3 
tool-bar 1.1.10 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-julia-client/commit/af1e70260f0ca61d3538c7a7ecf700ef2c948881.

**Comment by pvazteixeira** [comment]
Thanks!

**Comment by ssfrr** [comment]
I'm getting this again now with the recent update, when trying to run a cell in a `jmd` file using `alt-enter`.

**Atom**: 1.44.0 x64
**Electron**: 4.2.12
**OS**: linux 5.5.5-arch1-1
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.12.3


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/sfr/.atom/packages/ink/lib/editor/result.js:46

TypeError: Cannot read property 'length' of undefined
    at Result.attach (/home/sfr/github/ink/lib/editor/result.js:46:84)
    at new Result (/home/sfr/github/ink/lib/editor/result.js:25:10)
    at /packages/julia-client/lib/runtime/evaluation.coffee:54:29
```

### Commands

```
     -5:13.3.0 julia-client:copy-or-interrupt (textarea.xterm-helper-textarea)
     -5:13.3.0 julia-client:interrupt-julia (ink-terminal.julia-terminal)
     -5:02.7.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
  2x -5:01.0 core:backspace (input.hidden-input)
     -4:59.6.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -4:59.3.0 vim-mode-plus:delete (input.hidden-input)
  3x -4:58.9.0 vim-mode-plus:move-up-screen (input.hidden-input)
     -4:57.9.0 julia-client:run-cell (input.hidden-input)
  2x -4:31.9.0 ink-terminal:paste (textarea.xterm-helper-textarea)
  3x -1:55.6.0 julia-client:run-cell (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
audio 1.5.7 
fold-lines 0.2.2 
fonts 3.10.0 
indent-detective 0.4.0 
ink 0.12.3 
isotope-ui 2.8.5 
julia-client 0.12.3 
language-diff 0.7.0 
language-glsl 2.0.4 
language-julia 0.19.2 
language-latex 1.2.0 
language-weave 0.6.7 
latex-completions 0.3.6 
markdown-folding 0.3.1 
minimap 4.29.9 
minimap-git-diff 4.3.1 
monokai 0.24.0 
pdf-view 0.72.0 
tool-bar 1.2.1 
uber-juno 0.3.0 
vim-mode-plus 1.36.4 
zentabs 0.8.9 
```

**Comment by ssfrr** [comment]
oh, you know what it was? I had a code block without the ending "```".
