### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by shiyuzhao** [JunoLab/atom-ink#181]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.12

### Stack Trace

Uncaught TypeError: Cannot read property 'children' of undefined

```
At C:\Users\Shiyu\.atom\packages\ink\node_modules\xterm\lib\renderer\dom\DomRenderer.js:280

TypeError: Cannot read property 'children' of undefined
    at DomRenderer._setCellUnderline (/packages/ink/node_modules/xterm/lib/renderer/dom/DomRenderer.js:280:45)
    at DomRenderer._onLinkHover (/packages/ink/node_modules/xterm/lib/renderer/dom/DomRenderer.js:273:14)
    at /packages/ink/node_modules/xterm/lib/renderer/dom/DomRenderer.js:65:79)
    at Linkifier.EventEmitter.emit (/packages/ink/node_modules/xterm/lib/common/EventEmitter.js:70:20)
    at MouseZone.hoverCallback (/packages/ink/node_modules/xterm/lib/Linkifier.js:177:19)
    at MouseZoneManager._onHover (/packages/ink/node_modules/xterm/lib/ui/MouseZoneManager.js:106:18)
    at MouseZoneManager._onMouseMove (/packages/ink/node_modules/xterm/lib/ui/MouseZoneManager.js:84:18)
    at HTMLDivElement.MouseZoneManager._this._mouseMoveListener (/packages/ink/node_modules/xterm/lib/ui/MouseZoneManager.js:30:64)
```

### Commands

```
     -3:06.9.0 core:copy (input.hidden-input)
     -3:06.1.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -3:03.1.0 core:copy (input.hidden-input)
     -3:02.4.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -2:57.2.0 core:copy (input.hidden-input)
     -2:56.6.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -2:51.9.0 core:copy (input.hidden-input)
     -2:51.2.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -2:47.9.0 core:copy (input.hidden-input)
     -2:47.2.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -2:44.1.0 core:copy (input.hidden-input)
     -2:42.1.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -2:32.7.0 core:copy (input.hidden-input)
     -2:31.5.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -2:21.6.0 core:copy (input.hidden-input)
     -2:20.1.0 ink-terminal:paste (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
indent-detective 0.3.0 
ink 0.9.12 
julia-client 0.7.9 
language-julia 0.18.0 
latex-completions 0.3.5 
tool-bar 1.1.10 
uber-juno 0.2.0 
```

**Comment by xanfus** [comment]
Steps to reproduce: A. Move mouse within Julia's console tab. B. Move mouse from editable file tab to console tab.
**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Ubuntu 16.04.5 LTS MATE
**Thrown From**: ink package 0.9.12
Same stack trace. I've restarted "Atom" and switched off fallback renderer for Julia's console tab in Julia's settings. No notion of typeerror was observed from that point of time.
**Non-Core Packages**
ink 0.9.12 
julia-client 0.7.9 
language-julia 0.18.0 
latex-completions 0.3.5 
tool-bar 1.1.10 
uber-juno 0.2.0

**Comment by chriselrod** [comment]
**Atom**: 1.33.0-beta0 x64
**Electron**: 2.0.11
**OS**: "Fedora release
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.12


### Stack Trace

Uncaught TypeError: Cannot read property 'children' of undefined

```
At /home/chriselrod/.atom/packages/ink/node_modules/xterm/lib/renderer/dom/DomRenderer.js:280

TypeError: Cannot read property 'children' of undefined
    at DomRenderer._setCellUnderline (/packages/ink/node_modules/xterm/lib/renderer/dom/DomRenderer.js:280:45)
    at DomRenderer._onLinkLeave (/packages/ink/node_modules/xterm/lib/renderer/dom/DomRenderer.js:276:14)
    at /packages/ink/node_modules/xterm/lib/renderer/dom/DomRenderer.js:66:79)
    at Linkifier.EventEmitter.emit (/packages/ink/node_modules/xterm/lib/common/EventEmitter.js:70:20)
    at MouseZone.leaveCallback (/packages/ink/node_modules/xterm/lib/Linkifier.js:185:19)
    at MouseZoneManager._onHover (/packages/ink/node_modules/xterm/lib/ui/MouseZoneManager.js:95:31)
    at MouseZoneManager._onMouseMove (/packages/ink/node_modules/xterm/lib/ui/MouseZoneManager.js:84:18)
    at HTMLDivElement.MouseZoneManager._this._mouseMoveListener (/packages/ink/node_modules/xterm/lib/ui/MouseZoneManager.js:30:64)
```

### Commands

```
  2x -1:48.8.0 editor:newline (input.hidden-input)
  4x -1:46.9.0 core:backspace (input.hidden-input)
     -1:29.9.0 core:move-right (input.hidden-input)
     -1:29.4.0 core:move-left (input.hidden-input)
     -1:29.2.0 core:backspace (input.hidden-input)
  2x -1:28.3.0 core:move-right (input.hidden-input)
     -1:22.4.0 julia-client:run-block (input.hidden-input)
     -1:22.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  2x -1:17.7.0 core:move-up (input.hidden-input)
     -1:16.7.0 julia-client:run-block (input.hidden-input)
     -1:16.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:16.5.0 julia-client:run-block (input.hidden-input)
     -1:16.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  2x -1:13.5.0 julia-client:run-and-move (input.hidden-input)
     -0:16.6.0 julia-client:run-block (input.hidden-input)
     -0:16.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
GAS-x86_64-highlighter 0.3.7 
indent-detective 0.3.0 
ink 0.9.12 
julia-client 0.7.9 
language-julia 0.18.0 
latex-completions 0.3.5 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
This is an upstream isse (see https://github.com/xtermjs/xterm.js/issues/1747) and will be fixed once the next xterm.js version is out and we update to that.

**Comment by pfitzseb** [comment]
Should be fixed now.
