### ISSUE TITLE
atom-ink v0.9.12 installation error on Linux machines

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JunoLab/atom-ink#182]
I'm trying to update atom-ink from v0.9.11 to v0.9.12 on my Ubuntu/Linux machine (18.04 LTS) with Atom v.1.32.1, and got the following error. I didn't get any errors on my MacBook Pro and Windows 10 machines. Also, I didn't encounter any problem installing the previous atom-ink v0.9.11 on this Ubuntu/Linux machine. Please help!
```
$ apm install ink
Installing ink to /home/xxx/.atom/packages ✗

> ink@0.9.12 postinstall /tmp/apm-install-dir-118102-23774-1fv36d7.yz2c/node_modules/ink
> node scripts/postinstall.js


module.js:538
    throw err;
    ^

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/apm-install-dir-118102-23774-1fv36d7.yz2c/node_modules/ink/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118102-23774-1fv36d7.yz2c/package.json'
npm WARN apm-install-dir-118102-23774-1fv36d7.yz2c No description
npm WARN apm-install-dir-118102-23774-1fv36d7.yz2c No repository field.
npm WARN apm-install-dir-118102-23774-1fv36d7.yz2c No README data
npm WARN apm-install-dir-118102-23774-1fv36d7.yz2c No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ink@0.9.12 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ink@0.9.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.atom/.apm/_logs/2018-11-02T21_04_10_658Z-debug.log
```

**Comment by BoundaryValueProblems** [comment]
I have no idea, but I just remotely logged in to my linux machine, and ran the same installation command from the terminal. Then, it worked! The master branch of atom-ink was not updated during the period, so I'm very curious why it worked via remote login.

**Comment by pfitzseb** [comment]
Probably an intermittent connection (or maybe file system) problem.

**Comment by BoundaryValueProblems** [comment]
@pfitzseb, thanks! I'll close this issue now.
