### ISSUE TITLE
Uncaught TypeError: Cannot read property 'syncScrollArea' of undefined

### ISSUE THREAD

**Issue by Gigiux** [JunoLab/atom-ink#185]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Linux Mint
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.13

### Stack Trace

Uncaught TypeError: Cannot read property 'syncScrollArea' of undefined

```
At /home/gigiux/.atom/packages/ink/node_modules/xterm/lib/InputHandler.js:825

TypeError: Cannot read property 'syncScrollArea' of undefined
    at InputHandler.resetMode (/packages/ink/node_modules/xterm/lib/InputHandler.js:825:45)
    at /packages/ink/node_modules/xterm/lib/InputHandler.js:123:84
    at EscapeSequenceParser.parse (/packages/ink/node_modules/xterm/lib/EscapeSequenceParser.js:371:25)
    at InputHandler.parse (/packages/ink/node_modules/xterm/lib/InputHandler.js:200:22)
    at Terminal._innerWrite (/packages/ink/node_modules/xterm/lib/Terminal.js:876:32)
    at /packages/ink/node_modules/xterm/lib/Terminal.js:858:23
```

### Commands

```
     -0:21.8.0 julia-client:start-julia (atom-pane.pane.active)
```

### Non-Core Packages

```
indent-detective 0.3.1 
ink 0.9.13 
julia-client 0.7.11 
language-julia 0.18.0 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
This is an upstream bug that will be fixed once the next version of xterm.js is released.

**Comment by pfitzseb** [comment]
Should be fixed now.
