### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `domNode` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by mattcbro** [JunoLab/atom-ink#189]
Debugging Julia 0.6.4 tried to scroll the left sidebar.  [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Linux Mint
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.13

### Stack Trace

Uncaught TypeError: Cannot destructure property `domNode` of 'undefined' or 'null'.

```
At /home/matt/.atom/packages/ink/node_modules/etch/lib/patch.js:136

TypeError: Cannot destructure property `domNode` of 'undefined' or 'null'.
    at removeVirtualNode (/packages/ink/node_modules/etch/lib/patch.js:136:49)
    at removeVirtualNode (/packages/ink/node_modules/etch/lib/patch.js:145:9)
    at removeVirtualNode (/packages/ink/node_modules/etch/lib/patch.js:145:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:128:18)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at Object.update (/packages/ink/node_modules/etch/lib/component-helpers.js:62:5)
    at Workspace.filterItems (/packages/ink/lib/workspace/workspace.js:53:12)
    at Workspace.setItems (/packages/ink/lib/workspace/workspace.js:41:10)
    at Object.update (/packages/julia-client/lib/runtime/workspace.coffee:21:16)
    at debugmode (/packages/julia-client/lib/runtime/debugger.js:45:15)
    at /packages/julia-client/lib/runtime/debugger.js:19:5
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190133)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191574)
    at Object.detach (/packages/julia-client/lib/connection/client.coffee:116:14)
    at /packages/julia-client/lib/connection/local.coffee:82:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -5:28.7.0 julia-debug:step-into-function (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused.debug)
  3x -5:22.2.0 blur (button.btn.btn-primary.icon-sign-in)
  8x -5:18.1.0 julia-debug:step-to-next-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused.debug)
  3x -4:07.5.0 blur (button.btn.btn-primary.icon-arrow-down)
     -4:01.0 julia-debug:step-to-selected-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused.debug)
  5x -3:46.7.0 blur (button.btn.btn-primary.icon-jump-down)
     -3:43.3.0 julia-debug:step-to-next-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused.debug)
  2x -3:30.1.0 blur (button.btn.btn-primary.icon-arrow-down)
     -3:13.8.0 julia-debug:step-to-next-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused.debug)
  4x -3:06.9.0 blur (button.btn.btn-primary.icon-arrow-down)
     -2:47 julia-debug:step-to-next-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused.debug)
  3x -2:35.6.0 blur (button.btn.btn-primary.icon-arrow-down)
  2x -2:31.8.0 julia-debug:step-to-next-line (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused.debug)
  5x -2:12.7.0 blur (button.btn.btn-primary.icon-arrow-down)
     -0:11.9.0 julia-client:kill-julia (input.hidden-input)
  2x -0:00.2.0 blur (input.hidden-input)
```

### Non-Core Packages

```
ex-mode 0.18.0 
indent-detective 0.3.1 
ink 0.9.13 
julia-client 0.7.12 
language-julia 0.18.0 
latex-completions 0.3.6 
new-tab 0.5.3 
tool-bar 1.1.11 
uber-juno 0.2.0 
vim-mode-plus 1.34.0 
```

**Comment by pfitzseb** [comment]
Should be fixed now.
