### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by glwc** [JunoLab/atom-ink#190]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.14

### Stack Trace

Uncaught TypeError: Cannot read property 'get' of undefined

```
At C:\Users\crossg\.atom\packages\ink\node_modules\xterm\lib\Linkifier.js:139

TypeError: Cannot read property 'get' of undefined
    at _loop_1 (/packages/ink/node_modules/xterm/lib/Linkifier.js:139:29)
    at Linkifier._doLinkifyRow (/packages/ink/node_modules/xterm/lib/Linkifier.js:161:27)
    at Linkifier._linkifyRows (/packages/ink/node_modules/xterm/lib/Linkifier.js:68:22)
    at /packages/ink/node_modules/xterm/lib/Linkifier.js:53:69
```

### Commands

```
```

### Non-Core Packages

```
indent-detective 0.3.2 
ink 0.9.14 
julia-client 0.7.13 
language-julia 0.18.0 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by AshtonSBradley** [comment]
On MacOS I can reproduce this by copying code from an open .jl file into the console and running it
