### ISSUE TITLE
Uncaught TypeError: Cannot read property '_data' of undefined

### ISSUE THREAD

**Issue by narayanivedam** [JunoLab/atom-ink#191]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.15

### Stack Trace

Uncaught TypeError: Cannot read property '_data' of undefined

```
At /Users/nv/.atom/packages/ink/node_modules/xterm/lib/BufferLine.js:165

TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (/packages/ink/node_modules/xterm/lib/BufferLine.js:165:27)
    at Buffer._reflowSmaller (/packages/ink/node_modules/xterm/lib/Buffer.js:257:45)
    at Buffer._reflow (/packages/ink/node_modules/xterm/lib/Buffer.js:177:18)
    at Buffer.resize (/packages/ink/node_modules/xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/packages/ink/node_modules/xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/packages/ink/node_modules/xterm/lib/Terminal.js:1108:22)
    at Terminal.resize (/packages/ink/node_modules/xterm/lib/public/Terminal.js:53:20)
    at InkTerminal.resize (/packages/ink/lib/console2/console.js:211:19)
    at /packages/ink/lib/console2/console.js:70:16
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173759)
    at Workspace.didActivatePaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:424001)
    at Dock.subscriptions.l.paneContainer.onDidActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:468778)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1173759)
    at PaneContainer.didActivatePane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:446187)
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:463512)
    at Pane.focus (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:454965)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
    at Terminal.focus (/packages/ink/node_modules/xterm/lib/Terminal.js:162:27)
    at /packages/ink/node_modules/xterm/lib/Terminal.js:684:19)
```

### Commands

```
     -1:53.1.0 julia-client:interrupt-julia (textarea.xterm-helper-textarea)
     -1:15.6.0 application:open-file (input.hidden-input)
     -1:01.4.0 core:copy (input.hidden-input)
     -0:59.3.0 core:move-left (input.hidden-input)
     -0:58.2.0 core:paste (input.hidden-input)
  2x -0:52.7.0 editor:newline (input.hidden-input)
     -0:40.3.0 core:copy (input.hidden-input)
     -0:39.5.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -0:32.9.0 core:copy (input.hidden-input)
     -0:32.2.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -0:26.9.0 core:copy (input.hidden-input)
     -0:26.1.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -0:23 core:copy (input.hidden-input)
     -0:22.1.0 ink-terminal:paste (textarea.xterm-helper-textarea)
     -0:10.2.0 core:copy (input.hidden-input)
     -0:08.8.0 ink-terminal:paste (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
indent-detective 0.3.2 
ink 0.9.15 
julia-client 0.7.14 
language-julia 0.18.0 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by AshtonSBradley** [comment]
atom unusable for Julia due to this... any work around? or have I missed a move away from atom... what is recommended for stability?

**Comment by AshtonSBradley** [comment]
On MacOS I can reproduce this by copying code from an open .jl file into the console and running it

**Comment by damonturney** [comment]
I'm having the same problem.  All packages on Atom are fully updated.  Still getting this problem.

Why does this bug page say "closed"?  There is no solution explained here, so how can the issue be "closed"?  Explain please.
