### ISSUE TITLE
Uncaught TypeError: Cannot read property 'copyCellsFrom' of undefined

### ISSUE THREAD

**Issue by DatName** [JunoLab/atom-ink#192]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.0 x64
**Electron**: 2.0.18
**OS**: Ubuntu Disco
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.9.15

### Stack Trace

Uncaught TypeError: Cannot read property 'copyCellsFrom' of undefined

```
At /home/korelin/.atom/packages/ink/node_modules/xterm/lib/Buffer.js:257

TypeError: Cannot read property 'copyCellsFrom' of undefined
    at Buffer._reflowSmaller (/packages/ink/node_modules/xterm/lib/Buffer.js:257:45)
    at Buffer._reflow (/packages/ink/node_modules/xterm/lib/Buffer.js:177:18)
    at Buffer.resize (/packages/ink/node_modules/xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/packages/ink/node_modules/xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/packages/ink/node_modules/xterm/lib/Terminal.js:1108:22)
    at Terminal.resize (/packages/ink/node_modules/xterm/lib/public/Terminal.js:53:20)
    at InkTerminal.resize (/packages/ink/lib/console2/console.js:211:19)
    at /packages/ink/lib/console2/console.js:70:16
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190169)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191610)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/share/atom/resources/app/static/<embedded>:11:424370)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (/usr/share/atom/resources/app/static/<embedded>:14:38690)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190169)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191610)
    at PaneContainer.didChangeActiveItemOnPane (/usr/share/atom/resources/app/static/<embedded>:11:446653)
    at PaneContainer.didActivatePane (/usr/share/atom/resources/app/static/<embedded>:11:446130)
    at Pane.activate (/usr/share/atom/resources/app/static/<embedded>:11:463554)
    at Pane.focus (/usr/share/atom/resources/app/static/<embedded>:11:455007)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
    at Terminal.focus (/packages/ink/node_modules/xterm/lib/Terminal.js:162:27)
    at /packages/ink/node_modules/xterm/lib/Terminal.js:684:19)
```

### Commands

```
     -0:38.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:13.7.0 intentions:highlight (input.hidden-input)
     -0:13.6.0 core:cut (input.hidden-input)
     -0:13.3.0 core:save (input.hidden-input)
     -0:11.9.0 intentions:highlight (input.hidden-input)
     -0:11.2.0 core:backspace (input.hidden-input)
     -0:10.8.0 core:move-down (input.hidden-input)
     -0:10.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:10.3.0 editor:newline (input.hidden-input)
     -0:09.2.0 intentions:highlight (input.hidden-input)
     -0:09.1.0 julia-client:run-block (input.hidden-input)
     -0:09.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:07.9.0 intentions:highlight (input.hidden-input)
     -0:07.8.0 julia-client:run-block (input.hidden-input)
     -0:07.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:05.8.0 julia-client:clear-console (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
atom-black-ui 0.21.0 
atom-eclipse-syntax 0.0.6 
atom-html-preview 0.2.6 
atom-ide-ui 0.13.0 
atom-live-server 2.3.0 
autocomplete-html-entities 0.2.0 
autumn-highlighter-syntax 3.0.2 
busy-signal 2.0.0 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
code-macro 0.1.0 
docker 0.8.0 
ftp-remote-edit 0.13.6 
git-plus 8.6.1 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
grandson-of-obsidian 0.1.0 
gruvbox-dark-ui 1.1.0 
Hyrule-atom 1.2.1 
ide-html 0.5.0 
indent-detective 0.3.2 
ink 0.9.15 
intentions 1.1.5 
jackhammer-syntax 1.1.0 
juicy-syntax 1.0.5 
julia-client 0.7.14 
language-docker 1.1.8 
language-julia 0.18.0 
language-powershell 5.0.0 
language-protobuf 0.7.1 
latex-completions 0.3.6 
newton-dark-syntax 1.1.9 
pretty-json 2.0.3 
sombre-theme 1.0.0 
styri-syntax 1.0.0 
sunburst 0.3.0 
tablr 1.8.3 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by AshtonSBradley** [comment]
On MacOS I can reproduce this by copying code from an open .jl file into the console and running it

**Comment by cuihantao** [comment]
Same issue on macOS

**Comment by pfitzseb** [comment]
Are you still getting this with the latest ink version (v0.10.4)?

**Comment by cuihantao** [comment]
I just updated ink to v0.10.4. Will post more details if I encounter the issue again. Thanks for the follow up!
