### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-ink#194]
Happens every time I try:

1. Open a Julia file
2. Go to any line
3. Run "Julia Debug: Toggle Breakpoint" 

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.10.1

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /usr/share/atom/resources/app/static/<embedded>:14

TypeError: Invalid Point: (NaN, 0)
    at Function.t.exports.Point.assertValid (/usr/share/atom/resources/app/static/<embedded>:14:43907)
    at TextBuffer.clipPosition (/usr/share/atom/resources/app/static/<embedded>:11:496246)
    at MarkerLayer.t.exports.MarkerLayer.markPosition (/usr/share/atom/resources/app/static/<embedded>:14:72574)
    at DisplayMarkerLayer.t.exports.DisplayMarkerLayer.markBufferPosition (/usr/share/atom/resources/app/static/<embedded>:14:1097994)
    at TextEditor.markBufferPosition (/usr/share/atom/resources/app/static/<embedded>:11:28437)
    at BreakpointManager.insertView (/packages/ink/lib/debugger/breakpoints.js:121:21)
    at /packages/ink/lib/debugger/breakpoints.js:157:45
    at Array.forEach (<anonymous>)
    at BreakpointManager.add (/packages/ink/lib/debugger/breakpoints.js:157:26)
    at BreakpointManager.tryToggle (/packages/ink/lib/debugger/breakpoints.js:174:19)
    at /packages/julia-client/lib/runtime/debugger.js:175:17
    at Array.map (<anonymous>)
    at Object.togglebp (/packages/julia-client/lib/runtime/debugger.js:174:19)
    at /packages/julia-client/lib/package/commands.coffee:95:65)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1230796)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226930)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:285234)
```

### Commands

```
     -0:38.5.0 core:cancel (input.hidden-input)
     -0:37.3.0 command-palette:toggle (input.hidden-input)
     -0:33.3.0 core:confirm (input.hidden-input)
     -0:33.3.0 julia-debug:toggle-breakpoint (input.hidden-input)
     -0:30.7.0 inline:clear-current (input.hidden-input)
     -0:30.7.0 editor:consolidate-selections (input.hidden-input)
     -0:30.7.0 core:cancel (input.hidden-input)
     -0:27.7.0 key-binding-resolver:toggle (div.ReactVirtualized__Grid.ReactVirtualized__List)
  3x -0:27.7.0 settings-view:open (div.ReactVirtualized__Grid.ReactVirtualized__List)
  3x -0:24.8.0 key-binding-resolver:toggle (div.panels-item)
     -0:23.9.0 settings-view:open (div.panels-item)
     -0:03.9.0 julia-debug:toggle-breakpoint (input.hidden-input)
     -0:03.0 inline:clear-current (input.hidden-input)
     -0:03.0 editor:consolidate-selections (input.hidden-input)
     -0:03.0 core:cancel (input.hidden-input)
     -0:01.9.0 julia-debug:toggle-breakpoint (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-updater-linux 1.3.0 
cursor-history 0.13.2 
file-types 1.0.1 
framer-syntax 1.1.0 
framer-ui 2.0.0 
ftp-remote-edit 0.14.0 
highlight-selected 0.15.0 
hydrogen-launcher 1.2.2 
indent-detective 0.3.2 
ink 0.10.1 
julia-client 0.8.1 
language-cython 0.3.0 
language-docker 1.1.8 
language-fortran 2.1.7 
language-julia 0.18.0 
language-latex 1.2.0 
language-markdown 0.29.0 
language-mediawiki 2.2.0 
language-restructuredtext 1.1.2 
language-scheme 1.4.0 
latex 0.50.2 
latex-completions 0.3.6 
latex-friend 0.0.11 
latextools 0.8.5 
MagicPython 1.1.1 
markdown-preview-enhanced 0.15.10 
markdown-preview-plus 3.7.1 
markdown-toc 0.4.2 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-split-diff 0.3.7 
one-dork-syntax 2.2.3 
one-dork-ui 2.6.0 
pretty-json 2.0.3 
pristine-ui 1.1.11 
project-manager 3.3.6 
python-debugger 0.2.0 
python-indent 1.1.7 
python-isort 0.0.7 
remote-edit 1.9.0 
remote-ftp 2.2.2 
sort-lines 0.19.0 
sort-words 0.1.4 
sorter 1.2.1 
susave 0.4.0 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
teletype 0.13.3 
tool-bar 1.1.11 
uber-juno 0.2.0 
wordcount 3.0.0 
```

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/9b9c908467632cc383f21f284b9552606a5d012e and https://github.com/JunoLab/atom-julia-client/commit/7a426b7067f5e658c9cb0e9f0b0e8c32093c5146.
