### ISSUE TITLE
Ink - Failed to activate the ink package

### ISSUE THREAD

**Issue by ghost** [JunoLab/atom-ink#207]
i want to start with Julia, but..  i dont know how to install it so i researched.. and isnatlled the plugins/packages for it. im at the newest Atom version, is this the Problem?

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: LILITH
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.10.11

### Stack Trace

Failed to activate the ink package

```
At Cannot read property 'activate' of undefined

TypeError: Cannot read property 'activate' of undefined
    at Object.activate (/packages/ink/lib/ink.coffee:169:26)
    at Package.activateNow (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3539161)
    at measure (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538573)
    at Package.measure (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3536204)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538433)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538376)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:381112)
    at ~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:934678
    at r (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:929284)
    at n (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119384)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1119590)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -9:36 settings-view:install-packages-and-themes (atom-pane.pane.active)
     -8:58.1.0 core:move-left (input.hidden-input)
  3x -4:51.5.0 editor:newline (input.hidden-input)
     -4:35.2.0 core:move-left (input.hidden-input)
     -4:33.6.0 core:move-right (input.hidden-input)
     -4:32.7.0 julia-client:run-and-move (input.hidden-input)
     -3:58 editor:newline (input.hidden-input)
     -3:47.1.0 julia-client:run-and-move (input.hidden-input)
     -2:10.4.0 core:backspace (input.hidden-input)
 17x -2:00.5.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
ghoulish-ui 1.1.2 
indent-detective 0.3.3 
ink 0.10.11 
julia-client 0.8.10 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by hrestey** [comment]
I've got a similar issue.

Atom: 1.40.1
OS: MacOS

Thrown From: ink package 0.11.0

Stack Trace: 

Failed to activate the ink package

`TypeError: Cannot read property 'fromId' of undefined
    at InkConsole.module.exports.InkConsole.startConsole (/Users/Hayden/.atom/packages/proto-repl/lib/views/ink-console.coffee:29:29)
    at new InkConsole (/Users/Hayden/.atom/packages/proto-repl/lib/views/ink-console.coffee:24:6)
    at Repl.module.exports.Repl.consumeInk (/Users/Hayden/.atom/packages/proto-repl/lib/repl.coffee:50:23)
    at Object.consumeInk (/Users/Hayden/.atom/packages/proto-repl/lib/proto-repl.coffee:313:12)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1126065)
    at ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3290410)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3298696)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3295672)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3294996)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3292606)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3294856)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3294799)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382285)
    at o.forEach.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:377451)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:377435)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334486)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:336974)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334214)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:330008)
    at Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332031)
    at Package.enable (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3292391)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:375149)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2602116)`

**Comment by aviatesk** [comment]
proto-repl seems not to be maintained currently, and not compatible with the latest version of Ink.

**Comment by aviatesk** [comment]
@hrestey so you need to downgrade Ink, in order to make proto-repl work. I'm not sure which version is compatible with it tho.

**Comment by pfitzseb** [comment]
`apm install ink@0.10.12` should do the trick for you, @hrestey (and make sure not to upgrade again, obviously).
