### ISSUE TITLE
Cannot install Ink

### ISSUE THREAD

**Issue by AxlRUI** [JunoLab/atom-ink#212]
I tried a to purge and install atom again on ubuntu and nothing. 
> ink@0.10.12 postinstall /tmp/apm-install-dir-119717-13151-1ji4agk.eago/node_modules/ink
> node scripts/postinstall.js

Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119717-13151-1ji4agk.eago/package.json'
npm WARN apm-install-dir-119717-13151-1ji4agk.eago No description
npm WARN apm-install-dir-119717-13151-1ji4agk.eago No repository field.
npm WARN apm-install-dir-119717-13151-1ji4agk.eago No README data
npm WARN apm-install-dir-119717-13151-1ji4agk.eago No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ink@0.10.12 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the ink@0.10.12 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/axel/.atom/.apm/_logs/2019-08-17T16_46_17_378Z-debug.log

**Comment by twadleigh** [comment]
I see something something very similar:
```
apm install ink                                                                                                               
Installing ink to /home/tracy/.atom/packages ✗

> ink@0.11.6 postinstall /tmp/apm-install-dir-119928-20182-kzzg9v.6uto/node_modules/ink
> node scripts/postinstall.js


Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119928-20182-kzzg9v.6uto/package.json'
npm WARN apm-install-dir-119928-20182-kzzg9v.6uto No description
npm WARN apm-install-dir-119928-20182-kzzg9v.6uto No repository field.
npm WARN apm-install-dir-119928-20182-kzzg9v.6uto No README data
npm WARN apm-install-dir-119928-20182-kzzg9v.6uto No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ink@0.11.6 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the ink@0.11.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tracy/.atom/.apm/_logs/2019-10-28T21_44_59_366Z-debug.log
```
The contents of the log:
[2019-10-28T21_44_59_366Z-debug.log](https://github.com/JunoLab/atom-ink/files/3780792/2019-10-28T21_44_59_366Z-debug.log)

**Comment by fkastner** [comment]
I have the same problem.
I'm on Pop!_OS 19.10 (Ubuntu) with

```
$>atom -v
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```
and
```
$>apm -v
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 3.7.2
git 2.20.1
```
The installation fails with the same error message @AxlRUI and @twadleigh above had:
```
$>apm install ink
Installing ink to /home/kastner/.atom/packages ✗

> ink@0.11.6 postinstall /tmp/apm-install-dir-119931-29918-1y3a6qy.u69d/node_modules/ink
> node scripts/postinstall.js


Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119931-29918-1y3a6qy.u69d/package.json'
npm WARN apm-install-dir-119931-29918-1y3a6qy.u69d No description
npm WARN apm-install-dir-119931-29918-1y3a6qy.u69d No repository field.
npm WARN apm-install-dir-119931-29918-1y3a6qy.u69d No README data
npm WARN apm-install-dir-119931-29918-1y3a6qy.u69d No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ink@0.11.6 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the ink@0.11.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kastner/.atom/.apm/_logs/2019-10-31T16_29_38_647Z-debug.log
```
[2019-10-31T16_29_38_647Z-debug.log](https://github.com/JunoLab/atom-ink/files/3794907/2019-10-31T16_29_38_647Z-debug.log)

**Comment by pfitzseb** [comment]
Alright, thanks to some debugging with @fkastner, we now know that having a system `npm` installed might be causing the problems.

A couple of things you could try are:
- Uninstall `npm` before installing packages.
- Make sure `npm` isn't on your `PATH` before installing packages.
- Use [apx](https://github.com/Aerijo/apx) to install julia-client and ink.

I don't know if any of the above work since I can't repro the bug, but please give them a go if time permits and report back.

**Comment by MHellmund** [comment]
Doesn't help for me. After 
`sudo mv /usr/bin/npm /usr/bin/npm.bak `
I have no longer an npm in my $PATH, but I still got the same error as before and as reported above by fkastner

**Comment by pfitzseb** [comment]
Do you still have `node` on your path, and if you do, can you try removing that was well?

**Comment by fkastner** [comment]
FWIW I also tried removing both but it didn't help either.

**Comment by pfitzseb** [comment]
Did anyone give `apx` a try?

**Comment by MHellmund** [comment]
yes,
```
/usr/bin/npm install @aerijo/apx
~/node_modules/.bin/apx  install ink
```
worked without error.

**Comment by bramtayl** [comment]
apx worked for me too. Before I could install it I had to update npm to the latest version

**Comment by fkastner** [comment]
I tried it again today with a fresh install of atom 1.44.0 and it still doesn't work with the same error message.
Maybe we can get the atom developers to look at this again?

apx does work for me too.

**Comment by pierre-haessig** [comment]
On a fresh profile and new Atom installation on  Debian 10 (buster), `uber-juno` installation fail similarly on `ink`:

```
error Failed at the ink@0.12.3 postinstall script 
```

with the the main errors in the log seems to be:

```
2222 verbose stack Error: ink@0.12.3 postinstall: `node scripts/postinstall.js`
2222 verbose stack Exit status 134
2222 verbose stack     at EventEmitter.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
2222 verbose stack     at EventEmitter.emit (events.js:182:13)
2222 verbose stack     at ChildProcess.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2222 verbose stack     at ChildProcess.emit (events.js:182:13)
2222 verbose stack     at maybeClose (internal/child_process.js:961:16)
2222 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
````

I indeed have an installation of Debian's `node` (v10.15.2) and `npm` (5.8.0).

@MHellmund [shell commands](https://github.com/JunoLab/atom-ink/issues/212#issuecomment-552450010) to use [`apx`](https://github.com/Aerijo/apx) worked for me as well. Thanks!

**Comment by AGMoAnalyst** [comment]
I have same problem in widows 7 32-bit
my Julia is 1.5.0, Atom 1.5.0
tried reinstall uber-juno & julia-client but stll not install at all
