### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by baggepinnen** [JunoLab/atom-ink#220]
Not sure how to reproduce, it just starts randomly and I have to restart atom. 
Red error popups appear for every click in the editor

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'props' of undefined

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: Cannot read property 'props' of undefined
    at getKey (/packages/ink/node_modules/etch/lib/patch.js:161:22)
    at mapOldKeysToIndices (/packages/ink/node_modules/etch/lib/patch.js:166:17)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:102:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at Object.update (/packages/ink/node_modules/etch/lib/component-helpers.js:62:5)
    at Outline.filterItems (/packages/ink/lib/outline/outline.js:38:12)
    at Outline.setItems (/packages/ink/lib/outline/outline.js:31:10)
    at /packages/julia-client/lib/runtime/outline.js:55:16
    at throttled (/packages/markdown-preview-plus/node_modules/underscore/underscore.js:866:23)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at TextEditor.cursorMoved (/usr/share/atom/resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (/usr/share/atom/resources/app/static/<embedded>:11:547080)
    at Selection.marker.onDidChange.e (/usr/share/atom/resources/app/static/<embedded>:11:532223)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (/usr/share/atom/resources/app/static/<embedded>:14:2855767)
    at /usr/share/atom/resources/app/static/<embedded>:14:2851269
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at Marker.emitChangeEvent (/usr/share/atom/resources/app/static/<embedded>:14:73563)
    at Marker.update (/usr/share/atom/resources/app/static/<embedded>:14:72617)
    at Marker.setHeadPosition (/usr/share/atom/resources/app/static/<embedded>:14:68776)
    at DisplayMarker.setHeadBufferPosition (/usr/share/atom/resources/app/static/<embedded>:14:2853122)
    at DisplayMarker.setHeadScreenPosition (/usr/share/atom/resources/app/static/<embedded>:14:2853354)
```

### Commands

```
  5x -1:23.5.0 core:move-up (input.hidden-input)
  2x -0:50.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:47.8.0 core:move-right (input.hidden-input)
     -0:47.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:41.9.0 julia-client:run-block (input.hidden-input)
     -0:41.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:32.8.0 julia-client:run-block (input.hidden-input)
     -0:32.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
 10x -0:25.9.0 core:move-left (input.hidden-input)
     -0:22.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:21.4.0 core:copy (input.hidden-input)
  2x -0:19.9.0 core:move-down (input.hidden-input)
     -0:18.1.0 core:move-right (input.hidden-input)
     -0:17.9.0 core:move-down (input.hidden-input)
  2x -0:17.2.0 core:paste (input.hidden-input)
     -0:05.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-ide-datatip 0.11.0 
atom-ide-markdown-service 1.2.3 
auto-indent 0.5.0 
busy-signal 2.0.1 
file-icons 2.1.35 
highlight-selected 0.16.0 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.11.0 
julia-client 0.10.1 
language-julia 0.19.1 
language-latex 1.2.0 
latex 0.50.2 
latex-completions 0.3.6 
markdown-pdf 2.2.0 
markdown-preview-plus 3.9.3 
open-in-browser 0.5.2 
pdf-view 0.72.0 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

# Atom:
Version: 1.40.1
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.10.1
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "noAutoParenthesis": true
  },
  "juliaPath": "/home/fredrikb/julia-1.3.0-alpha/bin/julia",
  "uiOptions": {
    "enableMenu": true,
    "errorNotifications": false,
    "layouts": {
      "console": {
        "defaultLocation": "center",
        "split": "right"
      },
      "defaultPanes": {
        "documentation": false,
        "plotPane": false,
        "workspace": false
      },
      "openDefaultPanesOnStartUp": false,
      "plotPane": {
        "split": "up"
      }
    }
  }
}

# ink:
Version: 0.11.0
Config:
undefined

# uber-juno:
Version: 0.2.0
Config:
{
  "disable": true
}

# language-julia:
Version: 0.19.1
Config:
undefined

# language-weave:not installed

# indent-detective:
Version: 0.4.0
Config:
undefined

```
Julia Version 1.3.0-alpha.0
Commit 6c11e7c2c4 (2019-07-23 01:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = atom  -a

    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.10.1
  [70b36510] AutomaticDocstrings v0.1.1 [`~/.julia/dev/AutomaticDocstrings`]
  [aae01518] BandedMatrices v0.10.1
  [07f847a3] BasisFunctionExpansions v1.0.1
  [6e4b80f9] BenchmarkTools v0.4.3
  [5d742f6a] CSVFiles v0.16.0
  [3895d2a7] CUDAapi v1.1.0
  [8f4d0f93] Conda v1.3.0
  [3abffc1c] ControlSystemIdentification v0.1.5 [`~/.julia/dev/ControlSystemIdentification`]
  [a6e380b2] ControlSystems v0.5.3
  [3a865a2d] CuArrays v1.3.0 #master (https://github.com/JuliaGPU/CuArrays.jl.git)
  [717857b8] DSP v0.6.0
  [a93c6f00] DataFrames v0.19.3
  [864edb3b] DataStructures v0.17.0
  [9cd584b6] DifferentialDynamicProgramming v0.4.0 [`~/.julia/dev/DifferentialDynamicProgramming`]
  [09c11fbc] DiskDataProviders v0.1.0 [`~/.julia/dev/DiskDataProviders`]
  [7a1cc6ca] FFTW v0.3.0
  [5789e2e9] FileIO v1.0.7
  [587475ba] Flux v0.9.0 [`~/.julia/dev/Flux`]
  [ca11d760] FluxOptTools v0.1.0 [`~/.julia/dev/FluxOptTools`]
  [f6369f11] ForwardDiff v0.10.3
  [28b8d3ca] GR v0.41.0
  [14197337] GenericLinearAlgebra v0.1.1
  [f67ccb44] HDF5 v0.12.3
  [cd3eb016] HTTP v0.8.5
  [7073ff75] IJulia v1.20.0
  [6a3955dd] ImageFiltering v0.6.5
  [6218d12a] ImageMagick v0.7.5
  [916415d5] Images v0.18.0
  [d0351b0e] InspectDR v0.3.6
  [e5e0dc1b] Juno v0.7.2
  [1902f260] Knet v1.2.5
  [26dcc766] LPVSpectral v0.1.2
  [82ba68a1] LazyWAVFiles v0.1.0 [`~/.julia/dev/LazyWAVFiles`]
  [98b081ad] Literate v2.0.3
  [43172d54] LiterateWeave v0.1.0 [`~/.julia/dev/LiterateWeave`]
  [33e6dc65] MKL v0.0.0 #master (https://github.com/JuliaComputing/MKL.jl)
  [f0e99cf1] MLBase v0.8.0
  [cc2ba9b6] MLDataUtils v0.5.0
  [0987c9cc] MonteCarloMeasurements v0.4.1 [`~/.julia/dev/MonteCarloMeasurements`]
  [6f286f6a] MultivariateStats v0.7.0
  [872c559c] NNlib v0.6.0
  [429524aa] Optim v0.19.2
  [1dea7af3] OrdinaryDiffEq v5.15.1
  [58dd65bb] Plotly v0.2.0
  [f0f68f2c] PlotlyJS v0.12.5
  [91a5bcdd] Plots v0.26.2
  [3a141323] PolynomialRoots v0.2.0
  [438e738f] PyCall v1.91.2
  [d330b81b] PyPlot v2.8.2
  [a75dfa10] Robotlib v0.3.2+ [`~/.julia/dev/Robotlib`]
  [90137ffa] StaticArrays v0.11.0
  [2913bbd2] StatsBase v0.30.0
  [f3b207a7] StatsPlots v0.12.0
  [bd369af6] Tables v0.2.11
  [5e47fb64] TestImages v0.5.1
  [c751599d] ToeplitzMatrices v0.6.0
  [b8865327] UnicodePlots v1.1.0
  [8149f6b0] WAV v1.0.2
  [44d3d7a6] Weave v0.9.1
  [cd998857] Yota v0.1.3+ [`~/.julia/dev/Yota`]
  [e88e6eb3] Zygote v0.3.4 #master (https://github.com/FluxML/Zygote.jl.git)
  [700de1a5] ZygoteRules v0.1.0 [`~/.julia/dev/ZygoteRules`]
```

**Comment by pfitzseb** [comment]
Hm, I can't repro this. What exactly were you doing when the error popped up?

**Comment by baggepinnen** [comment]
I was selecting text, copying and pasting. It happens every now and then, and if I focus on another editor and then back, the problem goes away for a few minutes.

**Comment by MatFi** [comment]
Exact the same error here. It appears quite randomly one or two times a day. In my case the error is only thrown by a single tab and it helps to close and open it again. No need to restart Atom, even changes i have made are not lost. 

I'm using the AUR package atom-bin  with Manjaro 18.0.4

**Comment by pfitzseb** [comment]
Should be fixed by https://github.com/JunoLab/atom-ink/commit/d9491e94a0516433403786b3bf41bad9c1767076 (which will be in the next release).
