### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by tangcc35** [JunoLab/atom-ink#221]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At C:\Users\tangc\.atom\packages\ink\lib\docs\docpane.js:43

TypeError: Cannot read property 'then' of undefined
    at DocPane._search (/packages/ink/lib/docs/docpane.js:42:50)
    at HTMLElement.docpaneSearch (/packages/ink/lib/docs/docpane.js:26:36)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -8:03.5.0 core:redo (input.hidden-input)
  2x -7:59.7.0 find-and-replace:select-next (input.hidden-input)
 21x -7:53.4.0 core:confirm (textarea.xterm-helper-textarea)
     -0:35.7.0 docpane:search (input.hidden-input)
  5x -0:15.1.0 core:backspace (input.hidden-input)
  4x -0:10.5.0 docpane:search (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.11.0 
julia-client undefined 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Please re-install `julia-client`.
