### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new...

### ISSUE THREAD

**Issue by gzhang8** [JunoLab/atom-ink#222]
[Enter steps to reproduce:]

1. seems to happen randomly...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At /usr/share/atom/resources/app/static/<embedded>:11

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:108:23)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at Object.update (/packages/ink/node_modules/etch/lib/component-helpers.js:62:5)
    at Outline.filterItems (/packages/ink/lib/outline/outline.js:38:12)
    at Outline.setItems (/packages/ink/lib/outline/outline.js:31:10)
    at /packages/julia-client/lib/runtime/outline.js:55:16
    at throttled (/packages/ink/node_modules/underscore/underscore.js:866:23)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at TextEditor.cursorMoved (/usr/share/atom/resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (/usr/share/atom/resources/app/static/<embedded>:11:547080)
    at Selection.marker.onDidChange.e (/usr/share/atom/resources/app/static/<embedded>:11:532223)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (/usr/share/atom/resources/app/static/<embedded>:14:2855767)
    at /usr/share/atom/resources/app/static/<embedded>:14:2851269
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at Marker.emitChangeEvent (/usr/share/atom/resources/app/static/<embedded>:14:73563)
    at Marker.update (/usr/share/atom/resources/app/static/<embedded>:14:72617)
    at Marker.setHeadPosition (/usr/share/atom/resources/app/static/<embedded>:14:68776)
    at DisplayMarker.setHeadBufferPosition (/usr/share/atom/resources/app/static/<embedded>:14:2853122)
    at DisplayMarker.setHeadScreenPosition (/usr/share/atom/resources/app/static/<embedded>:14:2853354)
    at changePosition (/usr/share/atom/resources/app/static/<embedded>:11:522245)
    at Cursor.changePosition (/usr/share/atom/resources/app/static/<embedded>:11:530789)
```

### Commands

```
  2x -8:13.9.0 julia-client:run-and-move (input.hidden-input)
     -7:24.4.0 julia-client:kill-julia (input.hidden-input)
     -7:15.1.0 julia-client:clear-console (textarea.xterm-helper-textarea)
     -7:13 julia-client:run-all (input.hidden-input)
     -7:13 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -7:13 inline-results:clear-all (atom-text-editor.editor.is-focused)
     -5:43.6.0 core:select-all (input.hidden-input)
     -5:42.6.0 core:copy (input.hidden-input)
     -5:06.5.0 core:paste (input.hidden-input)
  5x -4:47.7.0 core:backspace (input.hidden-input)
  2x -3:42.1.0 core:paste (input.hidden-input)
     -1:34.8.0 core:copy (input.hidden-input)
     -0:57.8.0 core:paste (input.hidden-input)
     -0:56.7.0 core:save (input.hidden-input)
     -0:36 core:copy (input.hidden-input)
     -0:25.9.0 julia-client:run-and-move (input.hidden-input)
```

### Non-Core Packages

```
ftp-remote-edit 0.17.4 
indent-detective 0.4.0 
ink 0.11.0 
julia-client 0.10.1 
language-cmake 1.2.0 
language-glsl 2.0.4 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment]
Hopefully fixed by https://github.com/JunoLab/atom-ink/commit/d9491e94a0516433403786b3bf41bad9c1767076.
