### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by Andrew-YizhouLiu** [JunoLab/atom-ink#224]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'props' of undefined

```
At C:\Users\Andre\.atom\packages\ink\node_modules\etch\lib\patch.js:161

TypeError: Cannot read property 'props' of undefined
    at getKey (/packages/ink/node_modules/etch/lib/patch.js:161:22)
    at mapOldKeysToIndices (/packages/ink/node_modules/etch/lib/patch.js:166:17)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:102:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at Object.update (/packages/ink/node_modules/etch/lib/component-helpers.js:62:5)
    at Outline.filterItems (/packages/ink/lib/outline/outline.js:38:12)
    at Outline.setItems (/packages/ink/lib/outline/outline.js:31:10)
    at /packages/julia-client/lib/runtime/outline.js:55:16
    at throttled (/packages/ink/node_modules/underscore/underscore.js:866:23)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:547080)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:532223)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2858214)
    at ~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2853716
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at Marker.emitChangeEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:73563)
    at Marker.update (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:72617)
    at Marker.setRange (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:68232)
    at DisplayMarker.setBufferRange (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2855249)
    at modifySelection (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:532956)
```

### Commands

```
  2x -2:49.8.0 core:move-left (input.hidden-input)
     -2:47.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -2:45.9.0 core:save (input.hidden-input)
     -1:39.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:39.2.0 editor:newline (input.hidden-input)
     -1:33.2.0 autocomplete-plus:confirmIfNonDefault (input.hidden-input)
     -1:33.2.0 editor:newline (input.hidden-input)
     -1:32.9.0 core:save (input.hidden-input)
  7x -1:21.4.0 core:move-left (input.hidden-input)
     -1:17.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
  7x -1:13.1.0 core:backspace (input.hidden-input)
     -0:59 core:save (input.hidden-input)
     -0:58.6.0 editor:newline (input.hidden-input)
     -0:56.7.0 core:save (input.hidden-input)
     -0:49.4.0 application:open-file (input.hidden-input)
  3x -0:04.6.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.11.0 
jekyll 2.1.0 
julia-client 0.10.1 
language-julia 0.19.1 
language-liquid 0.7.0 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by DatName** [comment]
I am seeing the same error.
Atom version: 1.39.1

**Comment by pfitzseb** [comment]
Fixed on master and will be fixed in the next release.

**Comment by aminya** [comment]
When I open my `runtests.jl` file inside Atom I get this error.
```
C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11
Hide Stack Trace
TypeError: Cannot read property 'props' of undefined
    at getKey (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:161:22)
    at mapOldKeysToIndices (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:166:17)
    at updateChildren (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:102:9)
    at patch (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:18:9)
    at updateChildren (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:77:7)
    at patch (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:18:9)
    at updateChildren (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:77:7)
    at patch (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\patch.js:18:9)
    at updateSync (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\component-helpers.js:116:20)
    at Object.update (C:\Users\yahyaaba\.atom\packages\ink\node_modules\etch\lib\component-helpers.js:62:5)
    at Outline.filterItems (file:///C:/Users/yahyaaba/.atom/packages/ink/lib/outline/outline.js:38:12)
    at Outline.setItems (file:///C:/Users/yahyaaba/.atom/packages/ink/lib/outline/outline.js:31:10)
    at file:///C:/Users/yahyaaba/.atom/packages/julia-client/lib/runtime/outline.js:55:16
    at throttled (C:\Users\yahyaaba\.atom\packages\autocomplete-paths\node_modules\underscore\underscore.js:866:23)
    at Function.simpleDispatch (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1209208)
    at Emitter.emit (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1210649)
    at TextEditor.cursorMoved (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:33212)
    at Selection.markerDidChange (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:547080)
    at Selection.marker.onDidChange.e (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:532223)
    at Function.simpleDispatch (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1209208)
    at Emitter.emit (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14:2858214)
    at C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14:2853716
    at Function.simpleDispatch (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1209208)
    at Emitter.emit (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:1210649)
    at Marker.emitChangeEvent (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14:73563)
    at Marker.update (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14:72617)
    at Marker.setHeadPosition (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14:68776)
    at DisplayMarker.setHeadBufferPosition (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14:2855569)
    at DisplayMarker.setHeadScreenPosition (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14:2855801)
    at changePosition (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:522245)
    at Cursor.changePosition (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:530789)
    at Cursor.setScreenPosition (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:522211)
    at moveCursors.o (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:30282)
    at Array.forEach (<anonymous>)
    at transact (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:33144)
    at TextBuffer.transact (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:492111)
    at TextEditor.transact (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:24215)
    at TextEditor.moveCursors (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (C:\Users\yahyaaba\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11:96241)
```

**Comment by aminya** [comment]
> 
> 
> Fixed on master and will be fixed in the next release.

Sorry, I thought it is released already and this is a new issue.
