### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by racinmat** [JunoLab/atom-ink#228]
[Enter steps to reproduce:]

1. After opening atom with some julia script files, this exception is thown after clicking somewhere on the file, or even moving the cursor by keyboard arrows.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'props' of undefined

```
At C:\Users\racinsky\.atom\packages\ink\node_modules\etch\lib\patch.js:161

TypeError: Cannot read property 'props' of undefined
    at getKey (/packages/ink/node_modules/etch/lib/patch.js:161:22)
    at mapOldKeysToIndices (/packages/ink/node_modules/etch/lib/patch.js:166:17)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:102:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at Object.update (/packages/ink/node_modules/etch/lib/component-helpers.js:62:5)
    at Outline.filterItems (/packages/ink/lib/outline/outline.js:38:12)
    at Outline.setItems (/packages/ink/lib/outline/outline.js:31:10)
    at /packages/julia-client/lib/runtime/outline.js:55:16
    at later (/packages/indent-detective/node_modules/underscore/underscore.js:850:21)
```

### Commands

```
     -7:23.5.0 core:confirm (textarea.xterm-helper-textarea)
  2x -0:43.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.11.0 
julia-client 0.10.1 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by aviatesk** [comment]
dup of #224 :)

**Comment by racinmat** [comment]
Oh, my bad, atom told me this issue is not reported.
