### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by MdMahbubarRahman** [JunoLab/atom-ink#229]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'props' of undefined

```
At C:\Users\mahbu\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11

TypeError: Cannot read property 'props' of undefined
    at getKey (/packages/ink/node_modules/etch/lib/patch.js:161:22)
    at mapOldKeysToIndices (/packages/ink/node_modules/etch/lib/patch.js:166:17)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:102:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at Object.update (/packages/ink/node_modules/etch/lib/component-helpers.js:62:5)
    at Outline.filterItems (/packages/ink/lib/outline/outline.js:38:12)
    at Outline.setItems (/packages/ink/lib/outline/outline.js:31:10)
    at /packages/julia-client/lib/runtime/outline.js:55:16
    at throttled (/packages/indent-detective/node_modules/underscore/underscore.js:866:23)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:547080)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:532223)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2858214)
    at ~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2853716
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at Marker.emitChangeEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:73563)
    at Marker.update (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:72617)
    at Marker.setHeadPosition (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:68776)
    at DisplayMarker.setHeadBufferPosition (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2855569)
    at DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2855801)
```

### Commands

```
  5x -4:45.1.0 editor:newline (input.hidden-input)
  4x -2:26 core:move-down (input.hidden-input)
     -2:21 core:move-up (input.hidden-input)
     -2:20 autocomplete-plus:confirmIfNonDefault (input.hidden-input)
     -2:10.3.0 autocomplete-plus:confirm (input.hidden-input)
     -2:02.1.0 core:move-down (input.hidden-input)
     -2:01.6.0 core:move-up (input.hidden-input)
     -2:00.2.0 autocomplete-plus:confirmIfNonDefault (input.hidden-input)
     -1:46.8.0 autocomplete-plus:activate (input.hidden-input)
  6x -1:31.9.0 core:backspace (input.hidden-input)
  4x -0:50 core:move-right (input.hidden-input)
  2x -0:46.2.0 editor:newline (input.hidden-input)
  9x -0:22.8.0 core:select-down (input.hidden-input)
     -0:16.1.0 core:select-up (input.hidden-input)
     -0:16 core:select-down (input.hidden-input)
  4x -0:14.4.0 core:select-up (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.11.0 
julia-client 0.10.1 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by aviatesk** [comment]
see #224
