### ISSUE TITLE
Uncaught TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by tszanalytics** [JunoLab/atom-ink#231]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'props' of undefined

```
At C:\Users\millsjf\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:11

TypeError: Cannot read property 'props' of undefined
    at getKey (/packages/ink/node_modules/etch/lib/patch.js:161:22)
    at mapOldKeysToIndices (/packages/ink/node_modules/etch/lib/patch.js:166:17)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:102:9)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateChildren (/packages/ink/node_modules/etch/lib/patch.js:77:7)
    at patch (/packages/ink/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/ink/node_modules/etch/lib/component-helpers.js:116:20)
    at Object.update (/packages/ink/node_modules/etch/lib/component-helpers.js:62:5)
    at Outline.filterItems (/packages/ink/lib/outline/outline.js:38:12)
    at Outline.setItems (/packages/ink/lib/outline/outline.js:31:10)
    at /packages/julia-client/lib/runtime/outline.js:55:16
    at throttled (/packages/indent-detective/node_modules/underscore/underscore.js:866:23)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at TextEditor.cursorMoved (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:547080)
    at Selection.marker.onDidChange.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:532223)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2858214)
    at ~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2853716
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1210649)
    at Marker.emitChangeEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:73563)
    at Marker.update (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:72617)
    at Marker.setHeadPosition (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:68776)
    at DisplayMarker.setHeadBufferPosition (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2855569)
    at DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:2855801)
```

### Commands

```
     -3:02.0 julia-client:run-block (input.hidden-input)
     -3:02.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:29.2.0 julia-client:run-block (input.hidden-input)
     -2:29.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:22.1.0 julia-client:run-block (input.hidden-input)
     -2:22.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -2:18.4.0 julia-client:run-block (input.hidden-input)
     -2:18.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:30.5.0 julia-client:run-block (input.hidden-input)
     -1:30.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  2x -1:00.7.0 core:backspace (input.hidden-input)
     -0:55.9.0 core:save (input.hidden-input)
     -0:45 core:copy (input.hidden-input)
  6x -0:26 editor:newline (input.hidden-input)
  4x -0:24.2.0 core:move-up (input.hidden-input)
     -0:22.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.11.0 
julia-client 0.10.1 
language-julia 0.19.1 
latex-completions 0.3.6 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by VivaldoMendes** [comment]
The same is happening to me. Atom is not working at all.

**Comment by VivaldoMendes** [comment]
Apparently, the problem only appears when we open a Project.  If I open a file, without opening a Project, Atom seems to be working OK.

**Comment by pfitzseb** [comment]
Can you try updating to ink 0.11.1? Error should be fixed there.

**Comment by VivaldoMendes** [comment]
Sorry, but the ink package in my Windows 10 computer is already v. 0.11.1.

As I mentioned in my second comment, apparently,  the problem only appears if we open up a Project and a file within this project. If I start Atom, and open exactly the same file without expressively opening up the project that contains that file, Atom seems to work with no problems at all.
________________________________
De: Sebastian Pfitzner <notifications@github.com>
Enviado: 2 de outubro de 2019 14:11
Para: JunoLab/atom-ink <atom-ink@noreply.github.com>
Cc: Vivaldo Manuel Mendes <vivaldo.mendes@iscte-iul.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [JunoLab/atom-ink] Uncaught TypeError: Cannot read property 'props' of undefined (#231)


Can you try updating to ink 0.11.1? Error should be fixed there.

**Comment by pfitzseb** [comment]
You most definitely weren't on 0.11.1 when you first posted, I only released that version ~15mins ago ;) Would be good if you could try again after restarting Atom -- I haven't seen that issue since the fix was on master.

**Comment by VivaldoMendes** [comment]
Yes, you are right. I did the update to ink and now and it works perfectly.

I updated also the other package that could be updated (Tool Bar Menu to v. 1.1.13), and now 4 icons in that toolbar are not displayed:

Start Remote Julia Process
Interrupt Julia
Stop Julia
Run All

They do really work;  if we put the cursor on top of the open space that corresponds to their place in the Toolbar their name comes up and they work. The only point is that they can not be seen. It looks like this

[cid:d5f54cc4-b9ae-40c3-b38e-c9d5dbdb3053]

________________________________
De: Sebastian Pfitzner <notifications@github.com>
Enviado: 2 de outubro de 2019 14:30
Para: JunoLab/atom-ink <atom-ink@noreply.github.com>
Cc: Vivaldo Manuel Mendes <vivaldo.mendes@iscte-iul.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [JunoLab/atom-ink] Uncaught TypeError: Cannot read property 'props' of undefined (#231)


You most definitely weren't on 0.11.1 when you first posted, I only released that version ~15mins ago ;) Would be good if you could try again after restarting Atom -- I haven't seen that issue since the fix was on master.

**Comment by VivaldoMendes** [comment]
Sorry, but following my previous email, the buttons that are not showing up in the Tool Bar Menu, are apparently not working.

I tried to Interrupt Julia and it did not work:

[cid:619d9822-48fe-4379-a336-0b68543efbf5]
________________________________
De: Vivaldo Manuel Mendes <vivaldo.mendes@iscte-iul.pt>
Enviado: 2 de outubro de 2019 15:27
Para: JunoLab/atom-ink <reply@reply.github.com>
Assunto: RE: [JunoLab/atom-ink] Uncaught TypeError: Cannot read property 'props' of undefined (#231)

Yes, you are right. I did the update to ink and now and it works perfectly.

I updated also the other package that could be updated (Tool Bar Menu to v. 1.1.13), and now 4 icons in that toolbar are not displayed:

Start Remote Julia Process
Interrupt Julia
Stop Julia
Run All

They do really work;  if we put the cursor on top of the open space that corresponds to their place in the Toolbar their name comes up and they work. The only point is that they can not be seen. It looks like this

[cid:d5f54cc4-b9ae-40c3-b38e-c9d5dbdb3053]

________________________________
De: Sebastian Pfitzner <notifications@github.com>
Enviado: 2 de outubro de 2019 14:30
Para: JunoLab/atom-ink <atom-ink@noreply.github.com>
Cc: Vivaldo Manuel Mendes <vivaldo.mendes@iscte-iul.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [JunoLab/atom-ink] Uncaught TypeError: Cannot read property 'props' of undefined (#231)


You most definitely weren't on 0.11.1 when you first posted, I only released that version ~15mins ago ;) Would be good if you could try again after restarting Atom -- I haven't seen that issue since the fix was on master.
