### ISSUE TITLE
Cannot install ink v0.11.5 

### ISSUE THREAD

**Issue by amonpuschel** [JunoLab/atom-ink#234]
I'm on ubuntu disco
Fresh install of atom-1.40.1-amd64.deb.
After that:
```
apm install ink 
Installing ink to /home/os/.atom/packages 
✗

 ink@0.11.5 postinstall /tmp/apm-install-dir-11999-17258-wmwx05.r80oj/node_modules/ink
 node scripts/postinstall.js

Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11999-17258-wmwx05.r80oj/package.json'
npm WARN apm-install-dir-11999-17258-wmwx05.r80oj No description
npm WARN apm-install-dir-11999-17258-wmwx05.r80oj No repository field.
npm WARN apm-install-dir-11999-17258-wmwx05.r80oj No README data
npm WARN apm-install-dir-11999-17258-wmwx05.r80oj No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! ink@0.11.5 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the ink@0.11.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/os/.atom/.apm/_logs/2019-10-09T17_17_05_778Z-debug.log
```

[2019-10-09T17_17_05_778Z-debug.log](https://github.com/JunoLab/atom-ink/files/3708678/2019-10-09T17_17_05_778Z-debug.log)

```
> apm -v
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.16
git 2.20.1
```

**Comment by amonpuschel** [comment]
For some reason, doing the same installation procedure today resulted in SUCCESS :-)

**Comment by amonpuschel** [comment]
I'm sorry to reopen this issue, but the same problem happened on a different machine today.
I nearly emptied the machine ... at least regarding atom/npm/node/ ;-|
followed by a fresh atom install (via downloaded 1.40.1).
Hint: There is another package refusing to install: julia-client:

```
> @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install /tmp/apm-install-dir-119918-24344-2sr6ss.3gqr5/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
> prebuild-install || node scripts/install.js


Aborted (core dumped)
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.0.0-31-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-119918-24344-2sr6ss.3gqr5/node_modules/julia-client/node_modules/@pfitzseb/node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119918-24344-2sr6ss.3gqr5/package.json'
npm WARN apm-install-dir-119918-24344-2sr6ss.3gqr5 No description
npm WARN apm-install-dir-119918-24344-2sr6ss.3gqr5 No repository field.
npm WARN apm-install-dir-119918-24344-2sr6ss.3gqr5 No README data
npm WARN apm-install-dir-119918-24344-2sr6ss.3gqr5 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/os/.atom/.apm/_logs/2019-10-18T14_00_45_920Z-debug.log

```

**Comment by amonpuschel** [comment]
Others have similiar issues with other node projects:
https://github.com/sass/node-sass/issues/2641
I have the same error with node-sass, when I install npm from ubuntu repos (disco).
Maybe a hint, but my understanding is that atom is self contained regarding npm/node and so on. 
So it should not depend on the system's npm/node installation...right?

**Comment by amonpuschel** [comment]
And again....closing the issue.

This time I installed atom via ubuntu's **snap**. Same atom version, but can install ink (and julia-client) now!!

This was NOT neccessary on the other machine with the same issue.
