### ISSUE TITLE
Uncaught TypeError: this.scopes.some is not a function

### ISSUE THREAD

**Issue by MCMaurer** [JunoLab/atom-ink#268]
This just happened immediately upon trying to start Juno, not sure what other steps to outline.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.12.3

### Stack Trace

Uncaught TypeError: this.scopes.some is not a function

```
At /Users/MJ/.atom/packages/ink/lib/debugger/breakpoints.js:102

TypeError: this.scopes.some is not a function
    at BreakpointManager.appliesToEditor (/packages/ink/lib/debugger/breakpoints.js:102:24)
    at /packages/ink/lib/debugger/breakpoints.js:77:20
    at TextEditor.observeGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:7983)
    at /packages/ink/lib/debugger/breakpoints.js:76:26
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:424807)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:44778)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:446919)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:455763)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:457933)
    at TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1165207)
```

### Commands

```
     -0:25.2.0 julia-client:open-console (atom-pane.pane.active)
     -0:20.7.0 core:confirm (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
indent-detective 0.4.0 
ink 0.12.3 
julia-client 0.8.8 
language-julia 0.19.2 
latex-completions 0.3.6 
tool-bar 1.2.2 
uber-juno 0.3.0 
```

**Comment by ryanelandt** [comment]
I got this error after updating packages in Atom. The problem went away I updated Atom and all Atom packages. I'm using the same version for all packages as you are except for julia-client. You are using 0.8.8. I am using 0.12.3. You may try upgrading julia-client and see if this fixes the problem.

**Comment by pfitzseb** [comment]
Good catch -- julia-client 0.8.8 is most definitvely not compatible with ink 0.12.3.

**Comment by marty0801** [comment]
I've tripped over this several times. The problem was that I was installing Atom via apt-get (Ubuntu), which provides an out-of-date version. Installing the most recent version from the website has fixed my problem.
