### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by gasagna** [JunoLab/atom-ink#30]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.3.1
### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of null

```
At /Users/davide/.atom/packages/ink/lib/console/view.coffee:159

TypeError: Cannot read property 'classList' of null
    at ConsoleView.module.exports.ConsoleView.loading (/Users/davide/.atom/packages/ink/lib/console/view.coffee:159:50)
    at /Users/davide/.atom/packages/julia-client/lib/ui/console.coffee:43:41
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Loading.module.exports.Loading.update (/Users/davide/.atom/packages/ink/lib/util/loading.coffee:21:18)
    at Loading.module.exports.Loading.working (/Users/davide/.atom/packages/ink/lib/util/loading.coffee:12:27)
    at Object.module.exports.booting (/Users/davide/.atom/packages/julia-client/lib/connection/client.coffee:99:14)
    at Object.module.exports.jlprocess.start (/Users/davide/.atom/packages/julia-client/lib/connection/process.coffee:66:12)
    at /Users/davide/.atom/packages/julia-client/lib/package/commands.coffee:38:40
    at Server.<anonymous> (/Users/davide/.atom/packages/julia-client/lib/connection/tcp.coffee:41:7)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1257:10)
    at doNTCallback1 (node.js:430:9)
    at process._tickCallback (node.js:352:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ink, v0.3.1
julia-client, v0.3.0
language-julia, v0.5.0
latex-completions, v0.3.1
minimap, v4.19.0
project-manager, v2.7.5

# Dev
No dev packages
```

**Comment by korantir** [comment]
have same problem

**Comment by MikeInnes** [comment]
So this happens on startup?

**Comment by gasagna** [comment]
That's correct. Any test I can make to pinpoint the issue?

**Comment by MikeInnes** [comment]
No worries, I managed to reproduce. Thanks for the report!

**Comment by gasagna** [comment]
👍
