### ISSUE TITLE
Failed to activate the ink package

### ISSUE THREAD

**Issue by swadey** [JunoLab/atom-ink#38]
I get a failure when trying to update this package.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.4.0
### Stack Trace

Failed to activate the ink package

```
At this.ink.Console.fromId is not a function

TypeError: this.ink.Console.fromId is not a function
    at Object.module.exports.create (/Users/swade/.atom/packages/julia-client/lib/runtime/console.coffee:40:23)
    at Object.module.exports.activate (/Users/swade/.atom/packages/julia-client/lib/runtime/console.coffee:13:6)
    at Object.module.exports.consumeInk (/Users/swade/.atom/packages/julia-client/lib/runtime.coffee:20:11)
    at Object.module.exports.JuliaClient.consumeInk (/Users/swade/.atom/packages/julia-client/lib/julia-client.coffee:26:7)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:350:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  3x -1:03.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autohide-tree-view, v0.25.1
ink, v0.4.0
julia-client, v0.4.0
language-julia, v0.5.0
markdown-themeable-pdf, v0.10.2
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by dnbaker** [comment]
I'm also experiencing something very similar following [these directions](https://github.com/JunoLab/uber-juno/blob/master/setup.md) exactly.

The only difference is that I'm on OSX 10.12, and my error stack trace is as follows:

```
TypeError: Cannot read property 'add' of undefined
    at Object.module.exports.consumeInk (/Users/dnb/.atom/packages/julia-client/lib/runtime/debugger.coffee:78:10)
    at Object.module.exports.consumeInk (/Users/dnb/.atom/packages/julia-client/lib/runtime.coffee:21:15)
    at Object.module.exports.JuliaClient.consumeInk (/Users/dnb/.atom/packages/julia-client/lib/julia-client.coffee:33:7)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:355:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Users/dnb/.atom/packages/julia-client/node_modules/atom-package-deps/lib/index.js:29:35
    at undefined.next (native)
    at step (/Users/dnb/.atom/packages/julia-client/node_modules/atom-package-deps/lib/index.js:59:191)
    at /Users/dnb/.atom/packages/julia-client/node_modules/atom-package-deps/lib/index.js:59:368
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I am performing this with the Julia 0.5.0 release, even though the executable and package are labeled 0.6 for some strange reason.

**Comment by MikeInnes** [comment]
Most likely both are coming from outdated versions of the Ink package in Atom (and perhaps julia-client as well). Try updating those from Atom's settings view.

**Comment by pfitzseb** [comment]
If this still is a problem with the latest version of ink, please reopen this issue.

**Comment by davidzentlermunro** [comment]
I got similar issues after installing an ink update. I tried uninstalling juno and julia and reinstalling, and now get the following error when julia automatically tries to install ink (atom tells me I have installed v0.6.2 of ink, v0.5.11 of julia and v0.1.1 of uber-juno): 

```
Failed to activate the ink package
_etch2.default.initialize is not a function
Hide Stack Trace
```
```
TypeError: _etch2.default.initialize is not a function
    at new PlotPane (C:/Users/uctpdtz/.atom/packages/ink/lib/plots/pane.js:22:10)
    at Function.fromId (C:/Users/uctpdtz/.atom/packages/ink/lib/util/pane-item.js:74:36)
    at Function.activate (C:/Users/uctpdtz/.atom/packages/ink/lib/plots/pane.js:12:26)
    at Object.module.exports.Ink.activate (file:///C:/Users/uctpdtz/.atom/packages/ink/lib/ink.coffee:23:9)
    at Package.module.exports.Package.activateNow (C:\Atom\resources\app.asar\src\package.js:183:20)
    at C:\Atom\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Atom\resources\app.asar\src\package.js:92:15)
    at C:\Atom\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Atom\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Atom\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\uctpdtz\.atom\packages\julia-client\node_modules\atom-package-deps\lib\index.js:29:35
    at [object Generator].next (native)
    at step (C:\Users\uctpdtz\.atom\packages\julia-client\node_modules\atom-package-deps\lib\index.js:59:191)
    at C:\Users\uctpdtz\.atom\packages\julia-client\node_modules\atom-package-deps\lib\index.js:59:368
    at process._tickCallback (node.js:392:9)
The error was thrown from the ink package. This issue has already been reported.
View Issue

```

**Comment by maacl** [comment]
I can confirm same issue on:

1. Start Atom

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.6.2


### Stack Trace

Failed to activate the ink package

```
At _etch2.default.initialize is not a function

TypeError: _etch2.default.initialize is not a function
    at new PlotPane (/home/mac/.atom/packages/ink/lib/plots/pane.js:22:10)
    at Function.fromId (/home/mac/.atom/packages/ink/lib/util/pane-item.js:74:36)
    at Function.activate (/home/mac/.atom/packages/ink/lib/plots/pane.js:12:26)
    at Object.module.exports.Ink.activate (/home/mac/.atom/packages/ink/lib/ink.coffee:23:9)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:183:20)
    at /opt/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at /opt/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:538:21)
    at /opt/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:497:46)
    at /opt/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/mac/Dropbox/projects",
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.6.2
linter, v1.11.18
linter-clojure, v1.1.2
proto-repl, v1.4.12
proto-repl-charts, v0.4.0
recent-files-fuzzy-finder, v0.2.4
tool-bar, v1.0.1

# Dev
No dev packages
```
