### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by pfitzseb** [JunoLab/atom-ink#6]
This is something I'm not sure how to reproduce, but is also mentioned [here](http://discuss.junolab.org/t/announcing-julia-ide-work-in-atom/297/14?u=varanas).

Stack Trace:

```
SyntaxError: Unexpected end of input           # can be "Unexpected token [", too
  at Object.parse (native)
  at D:\Dokumente\Git\atom-julia-client\lib\connection\tcp.coffee:36:27
  at Socket.<anonymous> (D:\Dokumente\Git\atom-julia-client\lib\connection\tcp.coffee:17:9)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)
```

**Comment by pfitzseb** [comment]
Closed in favour of https://github.com/JunoLab/atom-julia-client/issues/19.
