### ISSUE TITLE
Uncaught TypeError: Cannot set property 'scrollPastEndOverride' of undefined

### ISSUE THREAD

**Issue by c123w** [JunoLab/atom-ink#82]
I got the error message below when I upgraded to Julia 0.5. Installing the newest version of Atom (1.10.2) from the Atom website seems to have solved the problem.

This may be the same issue as [#40](https://github.com/JunoLab/atom-ink/issues/40), but the error message is slightly different so I'm not quite sure.

**Atom Version**: 1.9.5
**System**: Ubuntu 16.04.1
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.5.2
### Stack Trace

Uncaught TypeError: Cannot set property 'scrollPastEndOverride' of undefined

```
At /home/foo/.atom/packages/ink/lib/console/view.coffee:143

TypeError: Cannot set property 'scrollPastEndOverride' of undefined
    at ink-console.ConsoleElement.inputView (/home/foo/.atom/packages/ink/lib/console/view.coffee:143:5)
    at ink-console.ConsoleElement.initView (/home/foo/.atom/packages/ink/lib/console/view.coffee:52:18)
    at ink-console.ConsoleElement.addItem (/home/foo/.atom/packages/ink/lib/console/view.coffee:57:15)
    at /home/foo/.atom/packages/ink/lib/console/view.coffee:25:36
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Console.module.exports.Console.push (/home/foo/.atom/packages/ink/lib/console/console.coffee:79:14)
    at Console.module.exports.Console.input (/home/foo/.atom/packages/ink/lib/console/console.coffee:127:8)
    at /home/foo/.atom/packages/ink/lib/console/console.coffee:67:42
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ink, v0.5.2 (active)
julia-client, v0.5.3 (active)
language-julia, v0.6.0 (inactive)
latex-completions, v0.3.1 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.43.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shashi** [comment]
I hit this too. Linux, Julia 0.5.0, Atom 1.8.0

**Comment by pfitzseb** [comment]
See it as an incentive to update Atom? :D

Should probably add some check for the Atom version though...

**Comment by JonWel** [comment]
@pfitzseb "See it as an incentive to update Atom?"
I was thinking that having installed through a .deb, the updates where automatic with apt.
Seems not (I was with 1.7.4, instead of 1.10.2).
If I remember well, Atom tell about available updates in Windows.
That's more an Atom issue though, and this bug was in deed somehow an incentive to update ^^.

**Comment by pfitzseb** [comment]
Alright, we now have a check for this: https://github.com/JunoLab/atom-ink/commit/2b4b86255ad46f4acdb172ffe9bbcba21f8fa48d
