### ISSUE TITLE
On updating language-julia: Error: Tried to create a gutter with a name that is already in use.

### ISSUE THREAD

**Issue by dlfivefifty** [JunoLab/atom-ink#91]
Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:36:15)
    at TextEditor.module.exports.TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3074:35)
    at Object.module.exports.init (/Users/solver/.atom/packages/ink/lib/debugger/breakpoints.coffee:40:8)
    at /Users/solver/.atom/packages/ink/lib/debugger/breakpoints.coffee:16:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.handleGrammarChange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3236:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:128:27)
    at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2812:35)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-registry.js:323:20
    at Set.forEach (native)
    at TextEditorRegistry.grammarAddedOrUpdated (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-registry.js:312:41)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/event-kit/lib/emitter.js:125:28)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:75:20)
    at Grammar.module.exports.Grammar.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar.js:223:48)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:543:25
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:120:55
    at parseContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:119:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:204:24
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by pfitzseb** [comment]
Feel free to reopen if this still is a problem with the latest version of Juno.
