### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by bethrice44** [JunoLab/atom-ink#98]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Users/er113/.atom/packages/ink/lib/console/history.coffee:26

TypeError: Cannot read property 'startsWith' of undefined
    at HistoryProvider.module.exports.HistoryProvider.matchesPrefix (/Users/er113/.atom/packages/ink/lib/console/history.coffee:26:22)
    at HistoryProvider.module.exports.HistoryProvider.getPrevious (/Users/er113/.atom/packages/ink/lib/console/history.coffee:32:35)
    at Console.module.exports.Console.moveHistory (/Users/er113/.atom/packages/ink/lib/console/console.coffee:282:16)
    at Console.module.exports.Console.previous (/Users/er113/.atom/packages/ink/lib/console/console.coffee:291:17)
    at Console.module.exports.Console.keyUp (/Users/er113/.atom/packages/ink/lib/console/console.coffee:300:10)
    at atom-text-editor.core:move-up (/Users/er113/.atom/packages/ink/lib/console/console.coffee:41:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/er113/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Users/er113/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/er113/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/er113/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/er113/Downloads/Atom 2.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Users/er113/Downloads/Atom 2.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:50.2.0 julia-client:start-julia (atom-text-editor.editor.is-focused)
     -0:39.8.0 julia-client:settings (atom-text-editor.editor.is-focused)
     -0:03.2.0 julia-client:open-console (div.package-detail.panels-item)
     -0:03.1.0 autocomplete-plus:cancel (atom-text-editor.editor)
     -0:00.2.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.6.1 (active)
julia-client, v0.5.10 (active)
language-julia, v0.10.0 (active)
latex-completions, v0.3.2 (active)
tool-bar, v1.0.1 (active)
uber-juno, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by timlod** [comment]
I get the same error whenever I invoke core:move-up in the console and there is no more command earlier in the history.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.5


### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /home/tim/.atom/packages/ink/lib/console/history.coffee:26

TypeError: Cannot read property 'startsWith' of undefined
    at HistoryProvider.module.exports.HistoryProvider.matchesPrefix (/packages/ink/lib/console/history.coffee:26:22)
    at HistoryProvider.module.exports.HistoryProvider.getPrevious (/packages/ink/lib/console/history.coffee:32:35)
    at Console.moveHistory (/packages/ink/lib/console/console.js:378:20)
    at Console.previous (/packages/ink/lib/console/console.js:388:21)
    at Console.keyUp (/packages/ink/lib/console/console.js:397:14)
    at /packages/ink/lib/console/console.js:44:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:23.5.0 editor:newline (input.hidden-input)
     -1:23.1.0 core:paste (input.hidden-input)
     -1:21.9.0 core:save (input.hidden-input)
  2x -1:19.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:17.9.0 console:evaluate (input.hidden-input)
  2x -1:17.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:12.6.0 core:backspace (input.hidden-input)
     -1:11.9.0 console:evaluate (input.hidden-input)
     -1:11.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  8x -1:11 core:backspace (input.hidden-input)
     -1:07.9.0 console:evaluate (input.hidden-input)
     -1:07.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  4x -1:06.2.0 core:move-up (input.hidden-input)
     -1:05.1.0 core:move-down (input.hidden-input)
     -1:01.1.0 core:move-up (input.hidden-input)
  2x -0:57.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
disable-keybindings 0.6.0 
emacs-plus 0.11.1 
ink 0.6.5 
julia-client 0.5.12 
language-julia 0.11.0 
latex-completions 0.3.2 
tool-bar 1.1.0 
uber-juno 0.1.1 
```
